# NCCL compatibility shim for RCCL root CMake.
# Keep this isolated to minimize future merge conflicts in root option blocks.

macro(rccl_define_nccl_compat_options)
  option(DEBUG                                   "Enable debug build compatibility flag"         OFF)
  option(ASAN                                    "Enable address sanitizer compatibility flag"   OFF)
  option(WERROR                                  "Treat warnings as errors compatibility flag"   OFF)
  option(PROFAPI                                 "Enable profiling API compatibility flag"       OFF)
  option(NVTX                                    "Enable NVTX compatibility flag"                ON)
  option(BUILD_DEBIAN_PACKAGE                    "Build Debian package compatibility flag"       OFF)
  option(BUILD_REDHAT_PACKAGE                    "Build Redhat package compatibility flag"       OFF)
  option(BUILD_TXZ_PACKAGE                       "Build TXZ package compatibility flag"          OFF)
  option(BUILD_CONDA_PACKAGE                     "Build Conda package compatibility flag"        OFF)
  option(BUILD_SRCTXZ_PACKAGE                    "Build source TXZ package compatibility flag"   OFF)
  option(BUILD_DOC_PACKAGE                       "Build documentation package compatibility flag" OFF)
  option(BUILD_PACKAGES                          "Build all packages compatibility flag"          OFF)

  set(RCCL_DEFAULT_BUILD_ADDRESS_SANITIZER OFF)
  if(ASAN)
    set(RCCL_DEFAULT_BUILD_ADDRESS_SANITIZER ON)
  endif()

  set(RCCL_DEFAULT_ROCTX ON)
  if(NOT NVTX)
    set(RCCL_DEFAULT_ROCTX OFF)
  endif()
endmacro()

macro(rccl_apply_nccl_compat_translations)
  if(DEBUG AND NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type" FORCE)
  endif()

  if(BUILD_PACKAGES)
    set(BUILD_DEBIAN_PACKAGE ON)
    set(BUILD_REDHAT_PACKAGE ON)
    set(BUILD_TXZ_PACKAGE ON)
    set(BUILD_CONDA_PACKAGE ON)
    set(BUILD_SRCTXZ_PACKAGE ON)
    set(BUILD_DOC_PACKAGE ON)
  endif()

  if(WERROR)
    add_compile_options(-Werror)
  endif()

  if(PROFAPI)
    add_compile_definitions(PROFAPI)
  endif()
endmacro()

macro(rccl_add_nccl_compat_package_targets)
  if(TARGET package)
    add_custom_target(debian_build DEPENDS package)
    add_custom_target(redhat_build DEPENDS package)
    add_custom_target(txz_build DEPENDS package)
    add_custom_target(conda_build DEPENDS package)
    add_custom_target(srctxz_build DEPENDS package)
    add_custom_target(doc_build DEPENDS package)
    add_custom_target(build_packages DEPENDS package)
  endif()
endmacro()
