ARG DISTRO=rockylinux
ARG VERSION=8
FROM ${DISTRO}:${VERSION}

ENV HOME=/root
ENV SHELL=/bin/bash
ENV BASH_ENV=/etc/bash.bashrc
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp
SHELL [ "/bin/bash", "-c" ]

ENV PATH=/usr/local/bin:${PATH}

ARG EXTRA_PACKAGES=""

RUN yum groupinstall -y "Development Tools" && \
    yum install -y epel-release && \
    yum install -y --allowerasing curl dpkg-devel python3-pip wget zlib-devel which git && \
    yum clean all && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install 'cmake==3.21'

# The Rock Tarball
RUN TARBALL=$(curl -fsSL "https://rocm.nightlies.amd.com/tarball-multi-arch/" | \
    grep -oE "\"name\": \"therock-dist-linux-multiarch-[^\"]+\", \"mtime\": [0-9.]+" | \
    sort -t' ' -k4 -g | \
    tail -1 | \
    sed 's/.*"name": "\([^"]*\)".*/\1/'); \
    test -n "${TARBALL}" || { echo "Error: no therock-dist-linux-multiarch-* tarball found" >&2; exit 1; }; \
    VERSION=$(echo "${TARBALL}" | sed -nE 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/p'); \
    test -n "${VERSION}" || { echo "Error: could not extract version from '${TARBALL}'" >&2; exit 1; }; \
    curl -fSL "https://rocm.nightlies.amd.com/tarball-multi-arch/${TARBALL}" \
        -o "/opt/rocm-${VERSION}-multiarch.tar.gz";

# Dev Mode (installs tarball, checks out rocprofiler-compute and installs it to the /opt/rocm)
ARG DEV_MODE=false
RUN if [ "${DEV_MODE}" = "true" ]; then \
        TARBALL=$(ls /opt/rocm-*-multiarch.tar.gz | head -1); \
        test -n "${TARBALL}" || { echo "Error: no tarball found in /opt" >&2; exit 1; }; \
        mkdir -p /opt/rocm && \
        tar -xf "${TARBALL}" -C /opt/rocm && \
        rm "${TARBALL}"; \
    fi

WORKDIR /home
SHELL [ "/bin/bash", "--login", "-c" ]
