"project: amdsmi":
- changed-files:
  - any-glob-to-any-file: 'projects/amdsmi/**/*'

"project: aqlprofile":
- changed-files:
  - any-glob-to-any-file: 'projects/aqlprofile/**/*'

"project: clr":
- changed-files:
  - any-glob-to-any-file: 'projects/clr/**/*'

"project: hip":
- changed-files:
  - any-glob-to-any-file: 'projects/hip/**/*'

"project: hipfile":
- changed-files:
  - any-glob-to-any-file:
    - 'projects/hipfile/**/*'
    - '.github/workflows/hipfile-*'

"project: hipother":
- changed-files:
  - any-glob-to-any-file: 'projects/hipother/**/*'

"project: hip-tests":
- changed-files:
  - any-glob-to-any-file: 'projects/hip-tests/**/*'

"project: rccl":
- changed-files:
  - any-glob-to-any-file: 'projects/rccl/**/*'

"project: rccl-tests":
- changed-files:
  - any-glob-to-any-file: 'projects/rccl-tests/**/*'

"project: rdc":
- changed-files:
  - any-glob-to-any-file: 'projects/rdc/**/*'

"project: rocm-core":
- changed-files:
  - any-glob-to-any-file: 'projects/rocm-core/**/*'

"project: rocminfo":
- changed-files:
  - any-glob-to-any-file: 'projects/rocminfo/**/*'

"project: rocm-smi-lib":
- changed-files:
  - any-glob-to-any-file: 'projects/rocm-smi-lib/**/*'

"project: rocprofiler":
- changed-files:
  - any-glob-to-any-file: 'projects/rocprofiler/**/*'

"project: rocprofiler-compute":
- changed-files:
  - any-glob-to-any-file: 'projects/rocprofiler-compute/**/*'

"project: rocprofiler-register":
- changed-files:
  - any-glob-to-any-file: 'projects/rocprofiler-register/**/*'

"project: rocprofiler-sdk":
- changed-files:
  - any-glob-to-any-file: 'projects/rocprofiler-sdk/**/*'

"project: rocprofiler-systems":
- changed-files:
  - any-glob-to-any-file: 'projects/rocprofiler-systems/**/*'

"project: rocprof-trace-decoder":
- changed-files:
  - any-glob-to-any-file: 'projects/rocprof-trace-decoder/**/*'

"project: rocr-runtime":
- changed-files:
  - any-glob-to-any-file: 'projects/rocr-runtime/**/*'

"project: rocshmem":
- changed-files:
  - any-glob-to-any-file: 'projects/rocshmem/**/*'

"project: roctracer":
- changed-files:
  - any-glob-to-any-file: 'projects/roctracer/**/*'

"project: rocjpeg":
- changed-files:
  - any-glob-to-any-file: 'projects/rocjpeg/**/*'

"project: rocdecode":
- changed-files:
  - any-glob-to-any-file: 'projects/rocdecode/**/*'

"project: rocr-debug-agent":
- changed-files:
  - any-glob-to-any-file: 'projects/rocr-debug-agent/**/*'

"project: rocdbgapi":
- changed-files:
  - any-glob-to-any-file: 'projects/rocdbgapi/**/*'

"shared: amdgpu-windows-interop":
- changed-files:
  - any-glob-to-any-file: 'shared/amdgpu-windows-interop/**/*'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - docs/**/*
    - '**/docs/**/*'
    - '*.md'

External CI:
- changed-files:
  - any-glob-to-any-file:
    - .azuredevops/**/*

github actions:
- changed-files:
  - any-glob-to-any-file:
    - .github/workflows/**/*
    - .github/scripts/**/*
    - .github/*.json
    - .github/*.yml
