default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Python import sorting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Check https://github.com/astral-sh/ruff-pre-commit#version-compatibility
    # for the latest ruff version supported by the hook.
    rev: v0.14.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Local hook: copyright header check
  - repo: local
    hooks:
      - id: copyright-header-check
        name: Copyright header check
        entry: bash -lc 'cd projects/rocprofiler-compute && python3 tools/copyright_header_check.py'
        language: system
        files: \.(py|hip|cpp)$
        pass_filenames: false
        stages: [pre-commit]

  # Local hook: hash consistency check
  - repo: local
    hooks:
      - id: hash-check
        name: Hash consistency check
        entry: bash -lc 'cd projects/rocprofiler-compute && python3 src/utils/hash_checker.py'
        language: system
        pass_filenames: false
        stages: [pre-commit]
