"""Gemini gate hook — native BeforeTool/AfterTool hooks (Task 4.6).

Gemini CLI now exposes project-level command hooks in
`<cwd>/.gemini/settings.json`. We use that native surface instead of
mutating user-global `~/.gemini/settings.json`:

1. A `BeforeTool` hook denies every non-`mcp_perfxpert_*` tool call
   until `mcp_perfxpert_intent_classify` has been observed returning
   in the current session.
2. An `AfterTool` hook writes a session-state file once
   `mcp_perfxpert_intent_classify` returns, lifting the gate for the
   remainder of that Gemini session.

Session-state location:
`<cwd>/.gemini/runtime/perfxpert-gate-<session_id>.json`.

This keeps the gate project-scoped and avoids touching Gemini's
user-global auth settings under `~/.gemini`.
"""

from __future__ import annotations

import json
import os
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from perfxpert.cli._backend import _prompt_adapter as pa
from perfxpert.cli._backend.protocol import GateHookUnsupported
from perfxpert.cli._gate_hooks import (
    GATE_HOOK_DISABLED_ENV,
    GATE_REJECTION_REASON_TEMPLATE,
    GATE_STATE_LIFTED_SENTINEL,
)


__all__ = [
    "GeminiGateHook",
    "GeminiGateInstallResult",
    "render_gate_script",
    "evaluate_gate_state",
]


_GATE_SCRIPT = r"""#!/usr/bin/env bash
# Perfxpert Gemini BeforeTool gate — generated by perfxpert-code install.
set -euo pipefail

_payload="$(cat -)"

_perfxpert_safe_sid() {
  case "$1" in
    ""|*[!A-Za-z0-9._-]*)
      return 1
      ;;
  esac
  printf '%s' "$1"
}

if command -v jq >/dev/null 2>&1; then
  _tool="$(printf '%s' "$_payload" | jq -r '.tool_name // ""')"
  _sid="$(printf '%s' "$_payload" | jq -r '.session_id // ""')"
else
  _tool="$(printf '%s' "$_payload" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("tool_name",""))')"
  _sid="$(printf '%s' "$_payload" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("session_id",""))')"
fi

if ! _sid="$(_perfxpert_safe_sid "$_sid")"; then
  _sid=""
fi

case "$_tool" in
  mcp_perfxpert_*)
    printf '%s\n' '{"decision":"allow"}'
    exit 0
    ;;
esac

_state_file=""
if [ -n "$_sid" ]; then
  _state_file="$(dirname "$0")/../runtime/perfxpert-gate-${_sid}.json"
fi
if [ -n "$_state_file" ] && [ -f "$_state_file" ]; then
  if grep -q '__GATE_SENTINEL__' "$_state_file"; then
    printf '%s\n' '{"decision":"allow"}'
    exit 0
  fi
fi

cat <<'JSON'
{"decision":"deny","reason":"__REJECTION_REASON__"}
JSON
exit 0
"""


_POST_SCRIPT = r"""#!/usr/bin/env bash
# Perfxpert Gemini AfterTool gate lift — writes state after
# mcp_perfxpert_intent_classify returns.
set -euo pipefail

_payload="$(cat -)"

_perfxpert_safe_sid() {
  case "$1" in
    ""|*[!A-Za-z0-9._-]*)
      return 1
      ;;
  esac
  printf '%s' "$1"
}

if command -v jq >/dev/null 2>&1; then
  _tool="$(printf '%s' "$_payload" | jq -r '.tool_name // ""')"
  _sid="$(printf '%s' "$_payload" | jq -r '.session_id // ""')"
else
  _tool="$(printf '%s' "$_payload" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("tool_name",""))')"
  _sid="$(printf '%s' "$_payload" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("session_id",""))')"
fi

if [ "$_tool" = "mcp_perfxpert_intent_classify" ]; then
  if ! _sid="$(_perfxpert_safe_sid "$_sid")"; then
    exit 0
  fi
  _state_dir="$(dirname "$0")/../runtime"
  mkdir -p "$_state_dir"
  _state_file="${_state_dir}/perfxpert-gate-${_sid}.json"
  printf '{"sentinel":"__GATE_SENTINEL__"}\n' > "$_state_file"
fi

printf '%s\n' '{"decision":"allow"}'
exit 0
"""


@dataclass(frozen=True)
class GeminiGateInstallResult:
    settings_path: Path
    hook_script: Path
    post_script: Path


def render_gate_script(classify_tool: str = "mcp_perfxpert_intent_classify") -> str:
    reason = GATE_REJECTION_REASON_TEMPLATE.format(classify_tool=classify_tool)
    reason_escaped = reason.replace("\\", "\\\\").replace('"', '\\"')
    body = _GATE_SCRIPT.replace("__REJECTION_REASON__", reason_escaped)
    return body.replace("__GATE_SENTINEL__", GATE_STATE_LIFTED_SENTINEL)


def render_post_script() -> str:
    return _POST_SCRIPT.replace("__GATE_SENTINEL__", GATE_STATE_LIFTED_SENTINEL)


def _settings_path(cwd: Path) -> Path:
    return cwd / ".gemini" / "settings.json"


class GeminiGateHook:
    """Installer for Gemini CLI's native project hook surface."""

    MARKER_SUBSTRING = "perfxpert-gate"

    def install(
        self,
        cwd: Path,
        *,
        classify_tool: str = "mcp_perfxpert_intent_classify",
    ) -> GeminiGateInstallResult:
        if os.environ.get(GATE_HOOK_DISABLED_ENV, "").strip() == "0":
            raise GateHookUnsupported(
                f"{GATE_HOOK_DISABLED_ENV}=0 — Gemini gate hook install skipped"
            )

        cwd = Path(cwd).expanduser().resolve()
        settings = _settings_path(cwd)
        script = cwd / ".gemini" / "hooks" / "perfxpert-gate.sh"
        post_script = cwd / ".gemini" / "hooks" / "perfxpert-gate-post.sh"

        script.parent.mkdir(parents=True, exist_ok=True)
        (cwd / ".gemini" / "runtime").mkdir(parents=True, exist_ok=True)

        pa.atomic_write(script, render_gate_script(classify_tool))
        pa.atomic_write(post_script, render_post_script())
        for p in (script, post_script):
            try:
                p.chmod(p.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
            except OSError:
                pass

        try:
            self._merge_settings(settings, script, post_script)
        except Exception:
            script.unlink(missing_ok=True)
            post_script.unlink(missing_ok=True)
            raise

        return GeminiGateInstallResult(
            settings_path=settings,
            hook_script=script,
            post_script=post_script,
        )

    def _merge_settings(
        self, settings: Path, pre_script: Path, post_script: Path
    ) -> None:
        settings.parent.mkdir(parents=True, exist_ok=True)
        existing: dict[str, Any] = {}
        if settings.is_file():
            try:
                existing = json.loads(settings.read_text())
            except json.JSONDecodeError as exc:
                raise GateHookUnsupported(
                    f"{settings} is not valid JSON: {exc}"
                )
            if not isinstance(existing, dict):
                raise GateHookUnsupported(
                    f"{settings} top-level must be an object"
                )

        hooks = existing.setdefault("hooks", {})
        if not isinstance(hooks, dict):
            raise GateHookUnsupported(
                f"{settings}['hooks'] must be an object"
            )

        pre_entry = _make_hook_entry(pre_script, marker=self.MARKER_SUBSTRING)
        post_entry = _make_hook_entry(post_script, marker=self.MARKER_SUBSTRING)

        hooks["BeforeTool"] = _merge_hook_list(
            hooks.get("BeforeTool"), pre_entry, marker=self.MARKER_SUBSTRING
        )
        hooks["AfterTool"] = _merge_hook_list(
            hooks.get("AfterTool"), post_entry, marker=self.MARKER_SUBSTRING
        )

        pa.atomic_write(settings, json.dumps(existing, indent=2) + "\n")

    def uninstall(self, cwd: Path) -> bool:
        cwd = Path(cwd).expanduser().resolve()
        settings = _settings_path(cwd)
        if settings.is_file():
            try:
                data = json.loads(settings.read_text())
            except json.JSONDecodeError:
                return False

            hooks = data.get("hooks")
            if isinstance(hooks, dict):
                for event in ("BeforeTool", "AfterTool"):
                    entries = hooks.get(event)
                    if not entries:
                        continue
                    hooks[event] = [
                        entry
                        for entry in entries
                        if self.MARKER_SUBSTRING not in json.dumps(entry)
                    ]
                    if not hooks[event]:
                        hooks.pop(event)
                if not hooks:
                    data.pop("hooks", None)
                pa.atomic_write(settings, json.dumps(data, indent=2) + "\n")

        for script in (
            cwd / ".gemini" / "hooks" / "perfxpert-gate.sh",
            cwd / ".gemini" / "hooks" / "perfxpert-gate-post.sh",
        ):
            try:
                script.unlink()
            except OSError:
                pass

        runtime_dir = cwd / ".gemini" / "runtime"
        for state_file in runtime_dir.glob("perfxpert-gate-*.json"):
            try:
                state_file.unlink()
            except OSError:
                pass
        if runtime_dir.is_dir():
            try:
                runtime_dir.rmdir()
            except OSError:
                pass

        hooks_dir = cwd / ".gemini" / "hooks"
        if hooks_dir.is_dir():
            try:
                hooks_dir.rmdir()
            except OSError:
                pass

        gemini_dir = cwd / ".gemini"
        if gemini_dir.is_dir():
            try:
                gemini_dir.rmdir()
            except OSError:
                pass
        return True


def evaluate_gate_state(
    tool_name: str,
    *,
    intent_classify_observed: bool,
    classify_tool: str = "mcp_perfxpert_intent_classify",
) -> dict[str, Any]:
    if tool_name.startswith("mcp_perfxpert_"):
        return {"allowed": True}
    if intent_classify_observed:
        return {"allowed": True}
    return {
        "allowed": False,
        "reason": GATE_REJECTION_REASON_TEMPLATE.format(
            classify_tool=classify_tool
        ),
    }


def _make_hook_entry(script: Path, *, marker: str) -> dict[str, Any]:
    return {
        "hooks": [
            {
                "type": "command",
                "command": str(script),
                "description": f"{marker} — perfxpert tool-priority gate (event-based)",
            }
        ]
    }


def _merge_hook_list(
    existing: Any, new_entry: dict[str, Any], *, marker: str
) -> list[dict[str, Any]]:
    if existing is None:
        return [new_entry]
    if isinstance(existing, list):
        filtered = [entry for entry in existing if marker not in json.dumps(entry)]
        filtered.append(new_entry)
        return filtered
    return [existing, new_entry]
