// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_CDNA3_MTBUF_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_CDNA3_MTBUF_H_

#include "rocjitsu/isa/arch/amdgpu/cdna3/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/cdna3/isa.h"
#include "rocjitsu/isa/arch/amdgpu/cdna3/operand.h"

namespace rocjitsu {
namespace cdna3 {

class TbufferLoadFormatXMtbuf : public Mtbuf {
public:
  TbufferLoadFormatXMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatXyMtbuf : public Mtbuf {
public:
  TbufferLoadFormatXyMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatXyzMtbuf : public Mtbuf {
public:
  TbufferLoadFormatXyzMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatXyzwMtbuf : public Mtbuf {
public:
  TbufferLoadFormatXyzwMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatXMtbuf : public Mtbuf {
public:
  TbufferStoreFormatXMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatXyMtbuf : public Mtbuf {
public:
  TbufferStoreFormatXyMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatXyzMtbuf : public Mtbuf {
public:
  TbufferStoreFormatXyzMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatXyzwMtbuf : public Mtbuf {
public:
  TbufferStoreFormatXyzwMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatD16XMtbuf : public Mtbuf {
public:
  TbufferLoadFormatD16XMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatD16XyMtbuf : public Mtbuf {
public:
  TbufferLoadFormatD16XyMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatD16XyzMtbuf : public Mtbuf {
public:
  TbufferLoadFormatD16XyzMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferLoadFormatD16XyzwMtbuf : public Mtbuf {
public:
  TbufferLoadFormatD16XyzwMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatD16XMtbuf : public Mtbuf {
public:
  TbufferStoreFormatD16XMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatD16XyMtbuf : public Mtbuf {
public:
  TbufferStoreFormatD16XyMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatD16XyzMtbuf : public Mtbuf {
public:
  TbufferStoreFormatD16XyzMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

class TbufferStoreFormatD16XyzwMtbuf : public Mtbuf {
public:
  TbufferStoreFormatD16XyzwMtbuf(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand vaddr;
  Operand srsrc;
  Operand soffset;
};

} // namespace cdna3
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_CDNA3_MTBUF_H_
