// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/addr_calc.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/smem.h"
#include "rocjitsu/isa/arch/amdgpu/shared/gfx12_cache_flags.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/mem_state.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <cstring>
#include <limits>
#include <memory>

namespace rocjitsu {
namespace gfx1250 {

const bool SLoadB32Smem::execute_registered_ = register_exec_fn<SLoadB32Smem>();

void SLoadB32Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadB64Smem::execute_registered_ = register_exec_fn<SLoadB64Smem>();

void SLoadB64Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 2;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadB128Smem::execute_registered_ = register_exec_fn<SLoadB128Smem>();

void SLoadB128Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 4;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadB256Smem::execute_registered_ = register_exec_fn<SLoadB256Smem>();

void SLoadB256Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 8;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadB512Smem::execute_registered_ = register_exec_fn<SLoadB512Smem>();

void SLoadB512Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 16;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadB96Smem::execute_registered_ = register_exec_fn<SLoadB96Smem>();

void SLoadB96Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 3;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadI8Smem::execute_registered_ = register_exec_fn<SLoadI8Smem>();

void SLoadI8Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 1;
  d->sign_extend = true;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadU8Smem::execute_registered_ = register_exec_fn<SLoadU8Smem>();

void SLoadU8Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 1;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadI16Smem::execute_registered_ = register_exec_fn<SLoadI16Smem>();

void SLoadI16Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 2;
  d->sign_extend = true;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SLoadU16Smem::execute_registered_ = register_exec_fn<SLoadU16Smem>();

void SLoadU16Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 2;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadB32Smem::execute_registered_ = register_exec_fn<SBufferLoadB32Smem>();

void SBufferLoadB32Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadB64Smem::execute_registered_ = register_exec_fn<SBufferLoadB64Smem>();

void SBufferLoadB64Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 2;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadB128Smem::execute_registered_ = register_exec_fn<SBufferLoadB128Smem>();

void SBufferLoadB128Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 4;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadB256Smem::execute_registered_ = register_exec_fn<SBufferLoadB256Smem>();

void SBufferLoadB256Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 8;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadB512Smem::execute_registered_ = register_exec_fn<SBufferLoadB512Smem>();

void SBufferLoadB512Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 16;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadB96Smem::execute_registered_ = register_exec_fn<SBufferLoadB96Smem>();

void SBufferLoadB96Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 3;
  d->elem_size = 4;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadI8Smem::execute_registered_ = register_exec_fn<SBufferLoadI8Smem>();

void SBufferLoadI8Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 1;
  d->sign_extend = true;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadU8Smem::execute_registered_ = register_exec_fn<SBufferLoadU8Smem>();

void SBufferLoadU8Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 1;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadI16Smem::execute_registered_ = register_exec_fn<SBufferLoadI16Smem>();

void SBufferLoadI16Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 2;
  d->sign_extend = true;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SBufferLoadU16Smem::execute_registered_ = register_exec_fn<SBufferLoadU16Smem>();

void SBufferLoadU16Smem::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::ScalarMemState>();
  d->dst_reg_base = wf.sgpr_alloc().base + inst_.sdata;
  d->num_dwords = 1;
  d->elem_size = 2;
  d->sign_extend = false;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::KMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->addr = smem_calculate_address(inst_, wf, d->elem_size * d->num_dwords);
  set_data(std::move(d));
}

const bool SDcacheInvSmem::execute_registered_ = register_exec_fn<SDcacheInvSmem>();

void SDcacheInvSmem::execute_impl(amdgpu::Wavefront &wf) { wf.cu().l1_scalar().invalidate_all(); }

const bool SAtcProbeSmem::execute_registered_ = register_exec_fn<SAtcProbeSmem>();

void SAtcProbeSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool SAtcProbeBufferSmem::execute_registered_ = register_exec_fn<SAtcProbeBufferSmem>();

void SAtcProbeBufferSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool SPrefetchInstSmem::execute_registered_ = register_exec_fn<SPrefetchInstSmem>();

void SPrefetchInstSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool SPrefetchInstPcRelSmem::execute_registered_ = register_exec_fn<SPrefetchInstPcRelSmem>();

void SPrefetchInstPcRelSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool SPrefetchDataSmem::execute_registered_ = register_exec_fn<SPrefetchDataSmem>();

void SPrefetchDataSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool SBufferPrefetchDataSmem::execute_registered_ =
    register_exec_fn<SBufferPrefetchDataSmem>();

void SBufferPrefetchDataSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool SPrefetchDataPcRelSmem::execute_registered_ = register_exec_fn<SPrefetchDataPcRelSmem>();

void SPrefetchDataPcRelSmem::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

} // namespace gfx1250
} // namespace rocjitsu
