// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_SOP1_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_SOP1_H_

#include "rocjitsu/isa/arch/amdgpu/gfx1250/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/isa.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/operand.h"

namespace rocjitsu {
namespace gfx1250 {

class SMovB32Sop1 : public Sop1 {
public:
  SMovB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SMovB64Sop1 : public Sop1 {
public:
  SMovB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCmovB32Sop1 : public Sop1 {
public:
  SCmovB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SCmovB64Sop1 : public Sop1 {
public:
  SCmovB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SBrevB32Sop1 : public Sop1 {
public:
  SBrevB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBrevB64Sop1 : public Sop1 {
public:
  SBrevB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SGetShaderCyclesU64Sop1 : public Sop1 {
public:
  SGetShaderCyclesU64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  static const bool execute_registered_;
};

class SCtzI32B32Sop1 : public Sop1 {
public:
  SCtzI32B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCtzI32B64Sop1 : public Sop1 {
public:
  SCtzI32B64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SClzI32U32Sop1 : public Sop1 {
public:
  SClzI32U32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SClzI32U64Sop1 : public Sop1 {
public:
  SClzI32U64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SClsI32Sop1 : public Sop1 {
public:
  SClsI32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SClsI32I64Sop1 : public Sop1 {
public:
  SClsI32I64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SSextI32I8Sop1 : public Sop1 {
public:
  SSextI32I8Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SSextI32I16Sop1 : public Sop1 {
public:
  SSextI32I16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBitset0B32Sop1 : public Sop1 {
public:
  SBitset0B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBitset0B64Sop1 : public Sop1 {
public:
  SBitset0B64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBitset1B32Sop1 : public Sop1 {
public:
  SBitset1B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBitset1B64Sop1 : public Sop1 {
public:
  SBitset1B64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBitreplicateB64B32Sop1 : public Sop1 {
public:
  SBitreplicateB64B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SAbsI32Sop1 : public Sop1 {
public:
  SAbsI32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SBcnt0I32B32Sop1 : public Sop1 {
public:
  SBcnt0I32B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SBcnt0I32B64Sop1 : public Sop1 {
public:
  SBcnt0I32B64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SBcnt1I32B32Sop1 : public Sop1 {
public:
  SBcnt1I32B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SBcnt1I32B64Sop1 : public Sop1 {
public:
  SBcnt1I32B64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SQuadmaskB32Sop1 : public Sop1 {
public:
  SQuadmaskB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SQuadmaskB64Sop1 : public Sop1 {
public:
  SQuadmaskB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SWqmB32Sop1 : public Sop1 {
public:
  SWqmB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SWqmB64Sop1 : public Sop1 {
public:
  SWqmB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SNotB32Sop1 : public Sop1 {
public:
  SNotB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SNotB64Sop1 : public Sop1 {
public:
  SNotB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SAndSaveexecB32Sop1 : public Sop1 {
public:
  SAndSaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndSaveexecB64Sop1 : public Sop1 {
public:
  SAndSaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SOrSaveexecB32Sop1 : public Sop1 {
public:
  SOrSaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SOrSaveexecB64Sop1 : public Sop1 {
public:
  SOrSaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SXorSaveexecB32Sop1 : public Sop1 {
public:
  SXorSaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SXorSaveexecB64Sop1 : public Sop1 {
public:
  SXorSaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SNandSaveexecB32Sop1 : public Sop1 {
public:
  SNandSaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SNandSaveexecB64Sop1 : public Sop1 {
public:
  SNandSaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SNorSaveexecB32Sop1 : public Sop1 {
public:
  SNorSaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SNorSaveexecB64Sop1 : public Sop1 {
public:
  SNorSaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SXnorSaveexecB32Sop1 : public Sop1 {
public:
  SXnorSaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SXnorSaveexecB64Sop1 : public Sop1 {
public:
  SXnorSaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot0SaveexecB32Sop1 : public Sop1 {
public:
  SAndNot0SaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot0SaveexecB64Sop1 : public Sop1 {
public:
  SAndNot0SaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SOrNot0SaveexecB32Sop1 : public Sop1 {
public:
  SOrNot0SaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SOrNot0SaveexecB64Sop1 : public Sop1 {
public:
  SOrNot0SaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot1SaveexecB32Sop1 : public Sop1 {
public:
  SAndNot1SaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot1SaveexecB64Sop1 : public Sop1 {
public:
  SAndNot1SaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SOrNot1SaveexecB32Sop1 : public Sop1 {
public:
  SOrNot1SaveexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SOrNot1SaveexecB64Sop1 : public Sop1 {
public:
  SOrNot1SaveexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot0WrexecB32Sop1 : public Sop1 {
public:
  SAndNot0WrexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot0WrexecB64Sop1 : public Sop1 {
public:
  SAndNot0WrexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot1WrexecB32Sop1 : public Sop1 {
public:
  SAndNot1WrexecB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SAndNot1WrexecB64Sop1 : public Sop1 {
public:
  SAndNot1WrexecB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand sdst_exec;
  Operand scc;
  Operand sdst_exec_in;
  static const bool execute_registered_;
};

class SMovrelsB32Sop1 : public Sop1 {
public:
  SMovrelsB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand m0;
  static const bool execute_registered_;
};

class SMovrelsB64Sop1 : public Sop1 {
public:
  SMovrelsB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand m0;
  static const bool execute_registered_;
};

class SMovreldB32Sop1 : public Sop1 {
public:
  SMovreldB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand m0;
  static const bool execute_registered_;
};

class SMovreldB64Sop1 : public Sop1 {
public:
  SMovreldB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand m0;
  static const bool execute_registered_;
};

class SMovrelsd2B32Sop1 : public Sop1 {
public:
  SMovrelsd2B32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand m0;
  static const bool execute_registered_;
};

class SGetPcI64Sop1 : public Sop1 {
public:
  SGetPcI64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand pc;
  static const bool execute_registered_;
};

class SSetPcI64Sop1 : public Sop1 {
public:
  SSetPcI64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  Operand pc;
  static const bool execute_registered_;
};

class SSwapPcI64Sop1 : public Sop1 {
public:
  SSwapPcI64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  Operand pc;
  Operand pc_in;
  static const bool execute_registered_;
};

class SRfeI64Sop1 : public Sop1 {
public:
  SRfeI64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  Operand pc;
  static const bool execute_registered_;
};

class SAddPcI64Sop1 : public Sop1 {
public:
  SAddPcI64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  Operand pc;
  static const bool execute_registered_;
};

class SSendmsgRtnB32Sop1 : public Sop1 {
public:
  SSendmsgRtnB32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SSendmsgRtnB64Sop1 : public Sop1 {
public:
  SSendmsgRtnB64Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBarrierSignalSop1 : public Sop1 {
public:
  SBarrierSignalSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBarrierSignalIsfirstSop1 : public Sop1 {
public:
  SBarrierSignalIsfirstSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SGetBarrierStateSop1 : public Sop1 {
public:
  SGetBarrierStateSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SBarrierInitSop1 : public Sop1 {
public:
  SBarrierInitSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  Operand m0;
  static const bool execute_registered_;
};

class SBarrierJoinSop1 : public Sop1 {
public:
  SBarrierJoinSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  static const bool execute_registered_;
};

class SAllocVgprSop1 : public Sop1 {
public:
  SAllocVgprSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  Operand scc;
  static const bool execute_registered_;
};

class SWakeupBarrierSop1 : public Sop1 {
public:
  SWakeupBarrierSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  static const bool execute_registered_;
};

class SSleepVarSop1 : public Sop1 {
public:
  SSleepVarSop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCeilF32Sop1 : public Sop1 {
public:
  SCeilF32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SFloorF32Sop1 : public Sop1 {
public:
  SFloorF32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class STruncF32Sop1 : public Sop1 {
public:
  STruncF32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SRndneF32Sop1 : public Sop1 {
public:
  SRndneF32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtF32I32Sop1 : public Sop1 {
public:
  SCvtF32I32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtF32U32Sop1 : public Sop1 {
public:
  SCvtF32U32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtI32F32Sop1 : public Sop1 {
public:
  SCvtI32F32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtU32F32Sop1 : public Sop1 {
public:
  SCvtU32F32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtF16F32Sop1 : public Sop1 {
public:
  SCvtF16F32Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtF32F16Sop1 : public Sop1 {
public:
  SCvtF32F16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCvtHiF32F16Sop1 : public Sop1 {
public:
  SCvtHiF32F16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SCeilF16Sop1 : public Sop1 {
public:
  SCeilF16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SFloorF16Sop1 : public Sop1 {
public:
  SFloorF16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class STruncF16Sop1 : public Sop1 {
public:
  STruncF16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

class SRndneF16Sop1 : public Sop1 {
public:
  SRndneF16Sop1(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand sdst;
  Operand ssrc0;
  static const bool execute_registered_;
};

} // namespace gfx1250
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_SOP1_H_
