// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_SOPK_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_SOPK_H_

#include "rocjitsu/isa/arch/amdgpu/gfx1250/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/isa.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/operand.h"

namespace rocjitsu {
namespace gfx1250 {

class SMovkI32Sopk : public Sopk {
public:
  SMovkI32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand simm16;
  static const bool execute_registered_;
};

class SVersionSopk : public Sopk {
public:
  SVersionSopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand simm16;
  static const bool execute_registered_;
};

class SCmovkI32Sopk : public Sopk {
public:
  SCmovkI32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand simm16;
  Operand scc;
  static const bool execute_registered_;
};

class SAddkCoI32Sopk : public Sopk {
public:
  SAddkCoI32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand simm16;
  Operand scc;
  static const bool execute_registered_;
};

class SMulkI32Sopk : public Sopk {
public:
  SMulkI32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand simm16;
  static const bool execute_registered_;
};

class SGetregB32Sopk : public Sopk {
public:
  SGetregB32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand sdst;
  Operand simm16;
  static const bool execute_registered_;
};

class SSetregB32Sopk : public Sopk {
public:
  SSetregB32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand simm16;
  Operand sdst;
  static const bool execute_registered_;
};

class SSetregImm32B32Sopk : public Sopk {
public:
  SSetregImm32B32Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  void implicit_uses(RegisterSet &uses) const override;
  Operand simm16;
  Operand literal;
  static const bool execute_registered_;
};

class SCallI64Sopk : public Sopk {
public:
  SCallI64Sopk(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  std::optional<int64_t> branch_offset_bytes() const override;
  Operand sdst;
  Operand simm16;
  Operand pc;
  Operand pc_in;
  static const bool execute_registered_;
};

} // namespace gfx1250
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_GFX1250_SOPK_H_
