// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/gfx1250/addr_calc.h"
#include "rocjitsu/isa/arch/amdgpu/gfx1250/vflat.h"
#include "rocjitsu/isa/arch/amdgpu/shared/gfx12_cache_flags.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/mem_state.h"
#include "rocjitsu/vm/amdgpu/register_access.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <cstring>
#include <limits>
#include <memory>

namespace rocjitsu {
namespace gfx1250 {

const bool FlatLoadU8Vflat::execute_registered_ = register_exec_fn<FlatLoadU8Vflat>();

void FlatLoadU8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadI8Vflat::execute_registered_ = register_exec_fn<FlatLoadI8Vflat>();

void FlatLoadI8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->sign_extend = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadU16Vflat::execute_registered_ = register_exec_fn<FlatLoadU16Vflat>();

void FlatLoadU16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadI16Vflat::execute_registered_ = register_exec_fn<FlatLoadI16Vflat>();

void FlatLoadI16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->sign_extend = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadB32Vflat::execute_registered_ = register_exec_fn<FlatLoadB32Vflat>();

void FlatLoadB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadB64Vflat::execute_registered_ = register_exec_fn<FlatLoadB64Vflat>();

void FlatLoadB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 2;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadB96Vflat::execute_registered_ = register_exec_fn<FlatLoadB96Vflat>();

void FlatLoadB96Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 3;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadB128Vflat::execute_registered_ = register_exec_fn<FlatLoadB128Vflat>();

void FlatLoadB128Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 4;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatStoreB8Vflat::execute_registered_ = register_exec_fn<FlatStoreB8Vflat>();

void FlatStoreB8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 1);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base, lane);
    d->store_data[lane * 1 + 0] = static_cast<uint8_t>(val0);
  }
  set_data(std::move(d));
}

const bool FlatStoreB16Vflat::execute_registered_ = register_exec_fn<FlatStoreB16Vflat>();

void FlatStoreB16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 2);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 2 + 0], &val0, 2);
  }
  set_data(std::move(d));
}

const bool FlatStoreB32Vflat::execute_registered_ = register_exec_fn<FlatStoreB32Vflat>();

void FlatStoreB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatStoreB64Vflat::execute_registered_ = register_exec_fn<FlatStoreB64Vflat>();

void FlatStoreB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 2;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatStoreB96Vflat::execute_registered_ = register_exec_fn<FlatStoreB96Vflat>();

void FlatStoreB96Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 3;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 12);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 12 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 12 + 4], &val1, 4);
    uint32_t val2 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 2, lane);
    std::memcpy(&d->store_data[lane * 12 + 8], &val2, 4);
  }
  set_data(std::move(d));
}

const bool FlatStoreB128Vflat::execute_registered_ = register_exec_fn<FlatStoreB128Vflat>();

void FlatStoreB128Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 4;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 16);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 16 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 16 + 4], &val1, 4);
    uint32_t val2 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 2, lane);
    std::memcpy(&d->store_data[lane * 16 + 8], &val2, 4);
    uint32_t val3 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 3, lane);
    std::memcpy(&d->store_data[lane * 16 + 12], &val3, 4);
  }
  set_data(std::move(d));
}

const bool FlatLoadD16U8Vflat::execute_registered_ = register_exec_fn<FlatLoadD16U8Vflat>();

void FlatLoadD16U8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadD16I8Vflat::execute_registered_ = register_exec_fn<FlatLoadD16I8Vflat>();

void FlatLoadD16I8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->sign_extend = true;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadD16B16Vflat::execute_registered_ = register_exec_fn<FlatLoadD16B16Vflat>();

void FlatLoadD16B16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadD16HiU8Vflat::execute_registered_ = register_exec_fn<FlatLoadD16HiU8Vflat>();

void FlatLoadD16HiU8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->d16_hi = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadD16HiI8Vflat::execute_registered_ = register_exec_fn<FlatLoadD16HiI8Vflat>();

void FlatLoadD16HiI8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->sign_extend = true;
  d->d16_hi = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadD16HiB16Vflat::execute_registered_ = register_exec_fn<FlatLoadD16HiB16Vflat>();

void FlatLoadD16HiB16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->d16_hi = true;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatStoreD16HiB8Vflat::execute_registered_ = register_exec_fn<FlatStoreD16HiB8Vflat>();

void FlatStoreD16HiB8Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 1;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 1);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base, lane);
    val0 >>= 16;
    d->store_data[lane * 1 + 0] = static_cast<uint8_t>(val0);
  }
  set_data(std::move(d));
}

const bool FlatStoreD16HiB16Vflat::execute_registered_ = register_exec_fn<FlatStoreD16HiB16Vflat>();

void FlatStoreD16HiB16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::STORECNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 2);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base, lane);
    val0 >>= 16;
    std::memcpy(&d->store_data[lane * 2 + 0], &val0, 2);
  }
  set_data(std::move(d));
}

const bool FlatAtomicSwapB32Vflat::execute_registered_ = register_exec_fn<FlatAtomicSwapB32Vflat>();

void FlatAtomicSwapB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SWAP;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicCmpswapB32Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicCmpswapB32Vflat>();

void FlatAtomicCmpswapB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::CMPSWAP;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicAddU32Vflat::execute_registered_ = register_exec_fn<FlatAtomicAddU32Vflat>();

void FlatAtomicAddU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::ADD;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicSubU32Vflat::execute_registered_ = register_exec_fn<FlatAtomicSubU32Vflat>();

void FlatAtomicSubU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SUB;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicSubClampU32Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicSubClampU32Vflat>();

void FlatAtomicSubClampU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SUB;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMinI32Vflat::execute_registered_ = register_exec_fn<FlatAtomicMinI32Vflat>();

void FlatAtomicMinI32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SMIN;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMinU32Vflat::execute_registered_ = register_exec_fn<FlatAtomicMinU32Vflat>();

void FlatAtomicMinU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::UMIN;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMaxI32Vflat::execute_registered_ = register_exec_fn<FlatAtomicMaxI32Vflat>();

void FlatAtomicMaxI32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SMAX;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMaxU32Vflat::execute_registered_ = register_exec_fn<FlatAtomicMaxU32Vflat>();

void FlatAtomicMaxU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::UMAX;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicAndB32Vflat::execute_registered_ = register_exec_fn<FlatAtomicAndB32Vflat>();

void FlatAtomicAndB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::AND;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicOrB32Vflat::execute_registered_ = register_exec_fn<FlatAtomicOrB32Vflat>();

void FlatAtomicOrB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::OR;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicXorB32Vflat::execute_registered_ = register_exec_fn<FlatAtomicXorB32Vflat>();

void FlatAtomicXorB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::XOR;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicIncU32Vflat::execute_registered_ = register_exec_fn<FlatAtomicIncU32Vflat>();

void FlatAtomicIncU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::INC;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicDecU32Vflat::execute_registered_ = register_exec_fn<FlatAtomicDecU32Vflat>();

void FlatAtomicDecU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::DEC;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicSwapB64Vflat::execute_registered_ = register_exec_fn<FlatAtomicSwapB64Vflat>();

void FlatAtomicSwapB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SWAP;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicCmpswapB64Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicCmpswapB64Vflat>();

void FlatAtomicCmpswapB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::CMPSWAP;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 16);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 16 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 16 + 4], &val1, 4);
    uint32_t val2 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 2, lane);
    std::memcpy(&d->store_data[lane * 16 + 8], &val2, 4);
    uint32_t val3 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 3, lane);
    std::memcpy(&d->store_data[lane * 16 + 12], &val3, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicAddU64Vflat::execute_registered_ = register_exec_fn<FlatAtomicAddU64Vflat>();

void FlatAtomicAddU64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::ADD;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicSubU64Vflat::execute_registered_ = register_exec_fn<FlatAtomicSubU64Vflat>();

void FlatAtomicSubU64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SUB;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMinI64Vflat::execute_registered_ = register_exec_fn<FlatAtomicMinI64Vflat>();

void FlatAtomicMinI64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SMIN;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMinU64Vflat::execute_registered_ = register_exec_fn<FlatAtomicMinU64Vflat>();

void FlatAtomicMinU64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::UMIN;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMaxI64Vflat::execute_registered_ = register_exec_fn<FlatAtomicMaxI64Vflat>();

void FlatAtomicMaxI64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SMAX;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMaxU64Vflat::execute_registered_ = register_exec_fn<FlatAtomicMaxU64Vflat>();

void FlatAtomicMaxU64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::UMAX;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicAndB64Vflat::execute_registered_ = register_exec_fn<FlatAtomicAndB64Vflat>();

void FlatAtomicAndB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::AND;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicOrB64Vflat::execute_registered_ = register_exec_fn<FlatAtomicOrB64Vflat>();

void FlatAtomicOrB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::OR;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicXorB64Vflat::execute_registered_ = register_exec_fn<FlatAtomicXorB64Vflat>();

void FlatAtomicXorB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::XOR;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicIncU64Vflat::execute_registered_ = register_exec_fn<FlatAtomicIncU64Vflat>();

void FlatAtomicIncU64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::INC;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicDecU64Vflat::execute_registered_ = register_exec_fn<FlatAtomicDecU64Vflat>();

void FlatAtomicDecU64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::DEC;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicCondSubU32Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicCondSubU32Vflat>();

void FlatAtomicCondSubU32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::SUB;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMinNumF32Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicMinNumF32Vflat>();

void FlatAtomicMinNumF32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FMIN;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMaxNumF32Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicMaxNumF32Vflat>();

void FlatAtomicMaxNumF32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FMAX;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicAddF64Vflat::execute_registered_ = register_exec_fn<FlatAtomicAddF64Vflat>();

void FlatAtomicAddF64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FADD;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicAddF32Vflat::execute_registered_ = register_exec_fn<FlatAtomicAddF32Vflat>();

void FlatAtomicAddF32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FADD;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicPkAddF16Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicPkAddF16Vflat>();

void FlatAtomicPkAddF16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FADD;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicPkAddBf16Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicPkAddBf16Vflat>();

void FlatAtomicPkAddBf16Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FADD;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMinNumF64Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicMinNumF64Vflat>();

void FlatAtomicMinNumF64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FMIN;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatAtomicMaxNumF64Vflat::execute_registered_ =
    register_exec_fn<FlatAtomicMaxNumF64Vflat>();

void FlatAtomicMaxNumF64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 8;
  d->num_elems = 1;
  d->is_load = amdgpu::gfx12_atomic_returns(inst_.th);
  d->atomic_op = amdgpu::AtomicOp::FMAX;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vsrc.opr_type_, vsrc.encoding_value_, vsrc.vgpr_msb_role());
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = amdgpu::RegisterAccess(cu).read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

const bool FlatPrefetchB8Vflat::execute_registered_ = register_exec_fn<FlatPrefetchB8Vflat>();

void FlatPrefetchB8Vflat::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

const bool FlatLoadMonitorB32Vflat::execute_registered_ =
    register_exec_fn<FlatLoadMonitorB32Vflat>();

void FlatLoadMonitorB32Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadMonitorB64Vflat::execute_registered_ =
    register_exec_fn<FlatLoadMonitorB64Vflat>();

void FlatLoadMonitorB64Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 2;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

const bool FlatLoadMonitorB128Vflat::execute_registered_ =
    register_exec_fn<FlatLoadMonitorB128Vflat>();

void FlatLoadMonitorB128Vflat::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base =
      wf.vgpr_alloc().base +
      *Isa::resolved_vgpr_offset(wf, vdst.opr_type_, vdst.encoding_value_, vdst.vgpr_msb_role());
  d->elem_size = 4;
  d->num_elems = 4;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::LOADCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx12(inst_.scope, inst_.th);
  d->non_temporal = 0;
  flat_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

} // namespace gfx1250
} // namespace rocjitsu
