// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna2/mtbuf.h"
#include "rocjitsu/isa/arch/amdgpu/rdna2/addr_calc.h"
#include "rocjitsu/isa/arch/amdgpu/shared/gfx10_cache_flags.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/mem_state.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <cstring>
#include <limits>
#include <memory>

namespace rocjitsu {
namespace rdna2 {

TbufferLoadFormatXMtbuf::TbufferLoadFormatXMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_x", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatXMtbuf>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatXMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferLoadFormatXyMtbuf::TbufferLoadFormatXyMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_xy", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatXyMtbuf>()),
      vdata(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatXyMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 4;
  d->num_elems = 2;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferLoadFormatXyzMtbuf::TbufferLoadFormatXyzMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_xyz", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatXyzMtbuf>()),
      vdata(96, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatXyzMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 4;
  d->num_elems = 3;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferLoadFormatXyzwMtbuf::TbufferLoadFormatXyzwMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_xyzw", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatXyzwMtbuf>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatXyzwMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 4;
  d->num_elems = 4;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferStoreFormatXMtbuf::TbufferStoreFormatXMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_x", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatXMtbuf>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatXMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 4);
  }
  set_data(std::move(d));
}

TbufferStoreFormatXyMtbuf::TbufferStoreFormatXyMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_xy", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatXyMtbuf>()),
      vdata(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatXyMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 2;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 4);
    uint32_t val1 = cu.read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val1, 4);
  }
  set_data(std::move(d));
}

TbufferStoreFormatXyzMtbuf::TbufferStoreFormatXyzMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_xyz", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatXyzMtbuf>()),
      vdata(96, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatXyzMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 3;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 12);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 12 + 0], &val0, 4);
    uint32_t val1 = cu.read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 12 + 4], &val1, 4);
    uint32_t val2 = cu.read_vgpr(data_base + 2, lane);
    std::memcpy(&d->store_data[lane * 12 + 8], &val2, 4);
  }
  set_data(std::move(d));
}

TbufferStoreFormatXyzwMtbuf::TbufferStoreFormatXyzwMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_xyzw", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatXyzwMtbuf>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatXyzwMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 4;
  d->num_elems = 4;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 16);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base + 0, lane);
    std::memcpy(&d->store_data[lane * 16 + 0], &val0, 4);
    uint32_t val1 = cu.read_vgpr(data_base + 1, lane);
    std::memcpy(&d->store_data[lane * 16 + 4], &val1, 4);
    uint32_t val2 = cu.read_vgpr(data_base + 2, lane);
    std::memcpy(&d->store_data[lane * 16 + 8], &val2, 4);
    uint32_t val3 = cu.read_vgpr(data_base + 3, lane);
    std::memcpy(&d->store_data[lane * 16 + 12], &val3, 4);
  }
  set_data(std::move(d));
}

TbufferLoadFormatD16XMtbuf::TbufferLoadFormatD16XMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_d16_x", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatD16XMtbuf>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatD16XMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferLoadFormatD16XyMtbuf::TbufferLoadFormatD16XyMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_d16_xy", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatD16XyMtbuf>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatD16XyMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 2;
  d->num_elems = 2;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferLoadFormatD16XyzMtbuf::TbufferLoadFormatD16XyzMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_d16_xyz", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatD16XyzMtbuf>()),
      vdata(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatD16XyzMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 2;
  d->num_elems = 3;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferLoadFormatD16XyzwMtbuf::TbufferLoadFormatD16XyzwMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_load_format_d16_xyzw", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferLoadFormatD16XyzwMtbuf>()),
      vdata(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &vaddr;
  src_operands_[1] = &srsrc;
  src_operands_[2] = &soffset;
  num_src_ = 3;
  num_dst_ = 1;
  flags_ |= MEMORY_OP;
}

void TbufferLoadFormatD16XyzwMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->dst_reg_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->elem_size = 2;
  d->num_elems = 4;
  d->is_load = true;
  d->wait_counter_type = amdgpu::WaitCounterType::VMCNT;
  d->d16_lo = true;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  set_data(std::move(d));
}

TbufferStoreFormatD16XMtbuf::TbufferStoreFormatD16XMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_d16_x", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatD16XMtbuf>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatD16XMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 2;
  d->num_elems = 1;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 2);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 2 + 0], &val0, 2);
  }
  set_data(std::move(d));
}

TbufferStoreFormatD16XyMtbuf::TbufferStoreFormatD16XyMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_d16_xy", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatD16XyMtbuf>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatD16XyMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 2;
  d->num_elems = 2;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 4);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 4 + 0], &val0, 2);
    uint32_t val1 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 4 + 2], &val1, 2);
  }
  set_data(std::move(d));
}

TbufferStoreFormatD16XyzMtbuf::TbufferStoreFormatD16XyzMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_d16_xyz", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatD16XyzMtbuf>()),
      vdata(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatD16XyzMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 2;
  d->num_elems = 3;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 6);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 6 + 0], &val0, 2);
    uint32_t val1 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 6 + 2], &val1, 2);
    uint32_t val2 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 6 + 4], &val2, 2);
  }
  set_data(std::move(d));
}

TbufferStoreFormatD16XyzwMtbuf::TbufferStoreFormatD16XyzwMtbuf(const MachineInst *inst)
    : Mtbuf("tbuffer_store_format_d16_xyzw", reinterpret_cast<const OpEncoding *>(inst),
            make_exec_fn<TbufferStoreFormatD16XyzwMtbuf>()),
      vdata(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      vaddr(64, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vaddr),
      srsrc(128, OperandType::OPR_SREG_NONULL, reinterpret_cast<const OpEncoding *>(inst)->srsrc),
      soffset(32, OperandType::OPR_SREG_M0_INL,
              reinterpret_cast<const OpEncoding *>(inst)->soffset) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &vaddr;
  src_operands_[2] = &srsrc;
  src_operands_[3] = &soffset;
  num_src_ = 4;
  num_dst_ = 0;
  flags_ |= MEMORY_OP;
}

void TbufferStoreFormatD16XyzwMtbuf::execute_impl(amdgpu::Wavefront &wf) {
  auto d = std::make_unique<amdgpu::VectorMemState>(amdgpu::GLOBAL_MEM);
  d->elem_size = 2;
  d->num_elems = 4;
  d->is_load = false;
  d->wait_counter_type = amdgpu::WaitCounterType::VSCNT;
  d->mtype = amdgpu::mtype_from_flags_gfx10(inst_.glc, inst_.dlc, inst_.slc);
  d->non_temporal = 0;
  mtbuf_calculate_addresses(inst_, wf, *d);
  auto &cu = wf.cu();
  uint64_t exec = wf.exec();
  uint32_t data_base = wf.vgpr_alloc().base + 0u + inst_.vdata;
  d->store_data.resize(wf.wf_size() * 8);
  for (uint32_t lane = 0; lane < wf.wf_size(); ++lane) {
    if (!(exec & (1ULL << lane)))
      continue;
    uint32_t val0 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 8 + 0], &val0, 2);
    uint32_t val1 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 8 + 2], &val1, 2);
    uint32_t val2 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 8 + 4], &val2, 2);
    uint32_t val3 = cu.read_vgpr(data_base, lane);
    std::memcpy(&d->store_data[lane * 8 + 6], &val3, 2);
  }
  set_data(std::move(d));
}

} // namespace rdna2
} // namespace rocjitsu
