---
oob:
  OOB_hip_module_load_over:
    <<: *level_4
    disabled: [windows, amd_windows, nvidia_linux, nvidia_windows]
    tags: [oob]
  OOB_hip_module_load_data_over:
    <<: *level_4
    disabled: [windows, amd_windows, nvidia_linux, nvidia_windows]
    tags: [oob]
  OOB_hiprtc_roundtrip_loads:
    <<: *level_4
    disabled: [windows, amd_windows, nvidia_linux, nvidia_windows]
    tags: [oob]