// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3_5/operand.h"
#include "rocjitsu/isa/isa_operand_simd_inl.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include <format>
#include <optional>
#include <stdexcept>
#include <string>

namespace rocjitsu {
namespace rdna3_5 {

namespace {
std::string reg_name(const char *prefix, int reg_num, int size_bits) {
  int count = size_bits / 32;
  if (count <= 1)
    return prefix + std::to_string(reg_num);
  return std::string(prefix) + "[" + std::to_string(reg_num) + ":" +
         std::to_string(reg_num + count - 1) + "]";
}
} // namespace

Operand::Operand(int size_bits, OperandType opr_type, int encoding_value)
    : AmdgpuIsaOperand<Isa>(size_bits, opr_type, encoding_value) {
  is_vgpr_ = is_vgpr_operand_type(opr_type);
}

Operand::Operand(int size_bits, OperandType opr_type, uint64_t literal64_value, bool is_literal64)
    : AmdgpuIsaOperand<Isa>(size_bits, opr_type, static_cast<int>(literal64_value)),
      literal64_value_(literal64_value), has_literal64_(is_literal64) {
  is_vgpr_ = is_vgpr_operand_type(opr_type);
}

std::optional<uint64_t> Operand::literal64_value() const {
  if (!has_literal64_)
    return std::nullopt;
  return literal64_value_;
}

std::string Operand::name() const {
  if (has_literal64_)
    return std::format("0x{:x}", literal64_value_);
  switch (opr_type_) {
  case OperandType::OPR_ATTR: {
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR0)
      return "attr0";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR1)
      return "attr1";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR2)
      return "attr2";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR3)
      return "attr3";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR4)
      return "attr4";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR5)
      return "attr5";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR6)
      return "attr6";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR7)
      return "attr7";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR8)
      return "attr8";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR9)
      return "attr9";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR10)
      return "attr10";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR11)
      return "attr11";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR12)
      return "attr12";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR13)
      return "attr13";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR14)
      return "attr14";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR15)
      return "attr15";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR16)
      return "attr16";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR17)
      return "attr17";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR18)
      return "attr18";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR19)
      return "attr19";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR20)
      return "attr20";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR21)
      return "attr21";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR22)
      return "attr22";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR23)
      return "attr23";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR24)
      return "attr24";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR25)
      return "attr25";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR26)
      return "attr26";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR27)
      return "attr27";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR28)
      return "attr28";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR29)
      return "attr29";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR30)
      return "attr30";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR31)
      return "attr31";
    if (encoding_value_ == OpSelAttr::OPR_ATTR_ATTR32)
      return "attr32";
    break;
  }
  case OperandType::OPR_DSMEM: {
    if (encoding_value_ == OpSelDsmem::OPR_DSMEM_DSMEM)
      return "dsmem";
    break;
  }
  case OperandType::OPR_EXEC: {
    if (encoding_value_ == OpSelExec::OPR_EXEC_EXEC)
      return "exec";
    break;
  }
  case OperandType::OPR_FLAT_SCRATCH: {
    if (encoding_value_ == OpSelFlatScratch::OPR_FLAT_SCRATCH_FLAT_SCRATCH)
      return "flat_scratch";
    break;
  }
  case OperandType::OPR_PC: {
    if (encoding_value_ == OpSelPc::OPR_PC_PC)
      return "pc";
    break;
  }
  case OperandType::OPR_SDST: {
    if (encoding_value_ >= OpSelSdst::OPR_SDST_SGPR_MIN &&
        encoding_value_ <= OpSelSdst::OPR_SDST_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSdst::OPR_SDST_SGPR_MIN, size_bits_);
    if (encoding_value_ >= OpSelSdst::OPR_SDST_TTMP_MIN &&
        encoding_value_ <= OpSelSdst::OPR_SDST_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSdst::OPR_SDST_TTMP_MIN, size_bits_);
    if (encoding_value_ == OpSelSdst::OPR_SDST_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSdst::OPR_SDST_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSdst::OPR_SDST_NULL)
      return "null";
    if (encoding_value_ == OpSelSdst::OPR_SDST_M0)
      return "m0";
    if (encoding_value_ == OpSelSdst::OPR_SDST_EXEC_LO)
      return "exec_lo";
    if (encoding_value_ == OpSelSdst::OPR_SDST_EXEC_HI)
      return "exec_hi";
    break;
  }
  case OperandType::OPR_SDST_EXEC: {
    if (encoding_value_ == OpSelSdstExec::OPR_SDST_EXEC_EXEC_LO)
      return "exec_lo";
    if (encoding_value_ == OpSelSdstExec::OPR_SDST_EXEC_EXEC_HI)
      return "exec_hi";
    break;
  }
  case OperandType::OPR_SDST_M0: {
    if (encoding_value_ == OpSelSdstM0::OPR_SDST_M0_M0)
      return "m0";
    break;
  }
  case OperandType::OPR_SDST_NULL: {
    if (encoding_value_ == OpSelSdstNull::OPR_SDST_NULL_NULL)
      return "null";
    break;
  }
  case OperandType::OPR_SMEM_OFFSET: {
    if (encoding_value_ >= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN &&
        encoding_value_ <= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN, size_bits_);
    if (encoding_value_ >= OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP_MIN &&
        encoding_value_ <= OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP_MIN,
                      size_bits_);
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_NULL)
      return "null";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_M0)
      return "m0";
    break;
  }
  case OperandType::OPR_SRC: {
    if (encoding_value_ >= OpSelSrc::OPR_SRC_SGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSrc::OPR_SRC_SGPR_MIN, size_bits_);
    if (encoding_value_ >= OpSelSrc::OPR_SRC_TTMP_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSrc::OPR_SRC_TTMP_MIN, size_bits_);
    if (encoding_value_ == OpSelSrc::OPR_SRC_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSrc::OPR_SRC_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSrc::OPR_SRC_NULL)
      return "null";
    if (encoding_value_ == OpSelSrc::OPR_SRC_M0)
      return "m0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_EXEC_LO)
      return "exec_lo";
    if (encoding_value_ == OpSelSrc::OPR_SRC_EXEC_HI)
      return "exec_hi";
    if (encoding_value_ >= OpSelSrc::OPR_SRC_POS_INT_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSrc::OPR_SRC_POS_INT_MIN);
    if (encoding_value_ >= OpSelSrc::OPR_SRC_NEG_INT_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSrc::OPR_SRC_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_SCC)
      return "src_scc";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_SHARED_BASE)
      return "src_shared_base";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_SHARED_LIMIT)
      return "src_shared_limit";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_PRIVATE_BASE)
      return "src_private_base";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_PRIVATE_LIMIT)
      return "src_private_limit";
    if (encoding_value_ >= OpSelSrc::OPR_SRC_VGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrc::OPR_SRC_VGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_LITERAL)
      return "literal";
    break;
  }
  case OperandType::OPR_SRC_VGPR: {
    if (encoding_value_ >= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_SRC_VGPR_OR_INLINE: {
    if (encoding_value_ >= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_POS_INT_MIN &&
        encoding_value_ <= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_POS_INT_MAX)
      return std::to_string(encoding_value_ -
                            OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_POS_INT_MIN);
    if (encoding_value_ >= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_NEG_INT_MIN &&
        encoding_value_ <= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_NEG_INT_MAX)
      return std::to_string(
          -(encoding_value_ - OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ >= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_VGPR_MIN,
                      size_bits_);
    break;
  }
  case OperandType::OPR_SREG: {
    if (encoding_value_ >= OpSelSreg::OPR_SREG_SGPR_MIN &&
        encoding_value_ <= OpSelSreg::OPR_SREG_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSreg::OPR_SREG_SGPR_MIN, size_bits_);
    if (encoding_value_ >= OpSelSreg::OPR_SREG_TTMP_MIN &&
        encoding_value_ <= OpSelSreg::OPR_SREG_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSreg::OPR_SREG_TTMP_MIN, size_bits_);
    if (encoding_value_ == OpSelSreg::OPR_SREG_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSreg::OPR_SREG_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSreg::OPR_SREG_NULL)
      return "null";
    break;
  }
  case OperandType::OPR_SREG_M0_INL: {
    if (encoding_value_ >= OpSelSregM0Inl::OPR_SREG_M0_INL_SGPR_MIN &&
        encoding_value_ <= OpSelSregM0Inl::OPR_SREG_M0_INL_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSregM0Inl::OPR_SREG_M0_INL_SGPR_MIN, size_bits_);
    if (encoding_value_ >= OpSelSregM0Inl::OPR_SREG_M0_INL_TTMP_MIN &&
        encoding_value_ <= OpSelSregM0Inl::OPR_SREG_M0_INL_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSregM0Inl::OPR_SREG_M0_INL_TTMP_MIN,
                      size_bits_);
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_NULL)
      return "null";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_M0)
      return "m0";
    if (encoding_value_ >= OpSelSregM0Inl::OPR_SREG_M0_INL_POS_INT_MIN &&
        encoding_value_ <= OpSelSregM0Inl::OPR_SREG_M0_INL_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSregM0Inl::OPR_SREG_M0_INL_POS_INT_MIN);
    if (encoding_value_ >= OpSelSregM0Inl::OPR_SREG_M0_INL_NEG_INT_MIN &&
        encoding_value_ <= OpSelSregM0Inl::OPR_SREG_M0_INL_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSregM0Inl::OPR_SREG_M0_INL_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSregM0Inl::OPR_SREG_M0_INL_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    break;
  }
  case OperandType::OPR_SSRC: {
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_SGPR_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSsrc::OPR_SSRC_SGPR_MIN, size_bits_);
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_TTMP_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSsrc::OPR_SSRC_TTMP_MIN, size_bits_);
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_NULL)
      return "null";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_M0)
      return "m0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_EXEC_LO)
      return "exec_lo";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_EXEC_HI)
      return "exec_hi";
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_POS_INT_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSsrc::OPR_SSRC_POS_INT_MIN);
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_NEG_INT_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSsrc::OPR_SSRC_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_SCC)
      return "src_scc";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_SHARED_BASE)
      return "src_shared_base";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_SHARED_LIMIT)
      return "src_shared_limit";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_PRIVATE_BASE)
      return "src_private_base";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_PRIVATE_LIMIT)
      return "src_private_limit";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_LITERAL)
      return "literal";
    break;
  }
  case OperandType::OPR_SSRC_LANESEL: {
    if (encoding_value_ >= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN &&
        encoding_value_ <= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN,
                      size_bits_);
    if (encoding_value_ >= OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP_MIN &&
        encoding_value_ <= OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP_MAX)
      return reg_name("ttmp", encoding_value_ - OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP_MIN,
                      size_bits_);
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_VCC_LO)
      return "vcc_lo";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_VCC_HI)
      return "vcc_hi";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_NULL)
      return "null";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_M0)
      return "m0";
    break;
  }
  case OperandType::OPR_SSRC_SPECIAL_SCC: {
    if (encoding_value_ == OpSelSsrcSpecialScc::OPR_SSRC_SPECIAL_SCC_SRC_SCC)
      return "src_scc";
    break;
  }
  case OperandType::OPR_TGT: {
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT0)
      return "mrt0";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT1)
      return "mrt1";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT2)
      return "mrt2";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT3)
      return "mrt3";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT4)
      return "mrt4";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT5)
      return "mrt5";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT6)
      return "mrt6";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRT7)
      return "mrt7";
    if (encoding_value_ == OpSelTgt::OPR_TGT_MRTZ)
      return "mrtz";
    if (encoding_value_ == OpSelTgt::OPR_TGT_POS0)
      return "pos0";
    if (encoding_value_ == OpSelTgt::OPR_TGT_POS1)
      return "pos1";
    if (encoding_value_ == OpSelTgt::OPR_TGT_POS2)
      return "pos2";
    if (encoding_value_ == OpSelTgt::OPR_TGT_POS3)
      return "pos3";
    if (encoding_value_ == OpSelTgt::OPR_TGT_POS4)
      return "pos4";
    if (encoding_value_ == OpSelTgt::OPR_TGT_PRIM)
      return "prim";
    if (encoding_value_ == OpSelTgt::OPR_TGT_DUAL_SRC_BLEND0)
      return "dual_src_blend0";
    if (encoding_value_ == OpSelTgt::OPR_TGT_DUAL_SRC_BLEND1)
      return "dual_src_blend1";
    break;
  }
  case OperandType::OPR_VCC: {
    if (encoding_value_ == OpSelVcc::OPR_VCC_VCC)
      return "vcc";
    break;
  }
  case OperandType::OPR_VGPR: {
    if (encoding_value_ >= OpSelVgpr::OPR_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelVgpr::OPR_VGPR_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelVgpr::OPR_VGPR_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_CLAUSE:
    return std::to_string(encoding_value_);
  case OperandType::OPR_DELAY:
    return std::to_string(encoding_value_);
  case OperandType::OPR_HWREG:
    return std::to_string(encoding_value_);
  case OperandType::OPR_LABEL:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SENDMSG:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SENDMSG_RTN:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SIMM16:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SIMM32:
    return std::format("0x{:x}", encoding_value_);
  case OperandType::OPR_SIMM8:
    return std::to_string(encoding_value_);
  case OperandType::OPR_VERSION:
    return std::to_string(encoding_value_);
  case OperandType::OPR_WAITCNT: {
    uint32_t expcnt = encoding_value_ & 0x7;
    uint32_t lgkmcnt = (encoding_value_ >> 4) & 0x3F;
    uint32_t vmcnt = (encoding_value_ >> 10) & 0x3F;
    return std::format("vmcnt({}) expcnt({}) lgkmcnt({})", vmcnt, expcnt, lgkmcnt);
  }
  case OperandType::OPR_WAITCNT_DEPCTR:
    return std::to_string(encoding_value_);
  case OperandType::OPR_WAIT_EVENT:
    return std::to_string(encoding_value_);
  }
  return std::to_string(encoding_value_);
}

std::optional<RegisterRef> Operand::to_register_ref() const {
  if (size_bits_ == 0)
    return std::nullopt;
  // Liveness tracks operands as contiguous 32-bit register lanes.
  const auto reg_width = static_cast<uint8_t>(size_bits_ > 32 ? size_bits_ / 32 : 1);
  switch (opr_type_) {
  case OperandType::OPR_ATTR: {
    break;
  }
  case OperandType::OPR_DSMEM: {
    break;
  }
  case OperandType::OPR_EXEC: {
    break;
  }
  case OperandType::OPR_FLAT_SCRATCH: {
    break;
  }
  case OperandType::OPR_PC: {
    break;
  }
  case OperandType::OPR_SDST: {
    if (encoding_value_ >= OpSelSdst::OPR_SDST_SGPR_MIN &&
        encoding_value_ <= OpSelSdst::OPR_SDST_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSdst::OPR_SDST_SGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_SDST_EXEC: {
    break;
  }
  case OperandType::OPR_SDST_M0: {
    break;
  }
  case OperandType::OPR_SDST_NULL: {
    break;
  }
  case OperandType::OPR_SMEM_OFFSET: {
    if (encoding_value_ >= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN &&
        encoding_value_ <= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC: {
    if (encoding_value_ >= OpSelSrc::OPR_SRC_SGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSrc::OPR_SRC_SGPR_MIN),
                         reg_width};
    if (encoding_value_ >= OpSelSrc::OPR_SRC_VGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_VGPR_MAX)
      return RegisterRef{RegClass::VGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSrc::OPR_SRC_VGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_SRC_VGPR: {
    if (encoding_value_ >= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN), reg_width};
    break;
  }
  case OperandType::OPR_SRC_VGPR_OR_INLINE: {
    if (encoding_value_ >= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ -
                                OpSelSrcVgprOrInline::OPR_SRC_VGPR_OR_INLINE_VGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SREG: {
    if (encoding_value_ >= OpSelSreg::OPR_SREG_SGPR_MIN &&
        encoding_value_ <= OpSelSreg::OPR_SREG_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSreg::OPR_SREG_SGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_SREG_M0_INL: {
    if (encoding_value_ >= OpSelSregM0Inl::OPR_SREG_M0_INL_SGPR_MIN &&
        encoding_value_ <= OpSelSregM0Inl::OPR_SREG_M0_INL_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSregM0Inl::OPR_SREG_M0_INL_SGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SSRC: {
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_SGPR_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSsrc::OPR_SSRC_SGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_SSRC_LANESEL: {
    if (encoding_value_ >= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN &&
        encoding_value_ <= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SSRC_SPECIAL_SCC: {
    break;
  }
  case OperandType::OPR_TGT: {
    break;
  }
  case OperandType::OPR_VCC: {
    break;
  }
  case OperandType::OPR_VGPR: {
    if (encoding_value_ >= OpSelVgpr::OPR_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelVgpr::OPR_VGPR_VGPR_MAX)
      return RegisterRef{RegClass::VGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelVgpr::OPR_VGPR_VGPR_MIN),
                         reg_width};
    break;
  }
  default:
    break;
  }
  return std::nullopt;
}

namespace {

uint32_t resolve_src_scalar(const amdgpu::Wavefront &wf, int ev) {
  if (ev == 102)
    return static_cast<uint32_t>(wf.scratch_base());
  if (ev == 103)
    return static_cast<uint32_t>(wf.scratch_base() >> 32);
  if (ev <= 105)
    return wf.cu().read_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev));
  if (ev == 106)
    return static_cast<uint32_t>(wf.vcc());
  if (ev == 107)
    return static_cast<uint32_t>(wf.vcc() >> 32);
  if (ev >= 108 && ev <= 123)
    return wf.cu().read_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev));
  if (ev == 124)
    return wf.m0();
  if (ev == 126)
    return static_cast<uint32_t>(wf.exec());
  if (ev == 127)
    return static_cast<uint32_t>(wf.exec() >> 32);
  if (ev >= 128 && ev <= 192)
    return static_cast<uint32_t>(ev - 128);
  if (ev >= 193 && ev <= 208)
    return static_cast<uint32_t>(static_cast<int32_t>(-(ev - 192)));
  if (ev == 230)
    return static_cast<uint32_t>(wf.scratch_base()); // SRC_FLAT_SCRATCH_BASE_LO
  if (ev == 231)
    return static_cast<uint32_t>(wf.scratch_base() >> 32); // SRC_FLAT_SCRATCH_BASE_HI
  if (ev == 240)
    return 0x3F000000u; // 0.5f
  if (ev == 241)
    return 0xBF000000u; // -0.5f
  if (ev == 242)
    return 0x3F800000u; // 1.0f
  if (ev == 243)
    return 0xBF800000u; // -1.0f
  if (ev == 244)
    return 0x40000000u; // 2.0f
  if (ev == 245)
    return 0xC0000000u; // -2.0f
  if (ev == 246)
    return 0x40800000u; // 4.0f
  if (ev == 247)
    return 0xC0800000u; // -4.0f
  if (ev == 248)
    return 0x3E22F983u; // 1/(2*pi)
  if (ev == 235)
    return static_cast<uint32_t>(wf.shared_aperture_base() >> 32); // SRC_SHARED_BASE
  if (ev == 236)
    return static_cast<uint32_t>(wf.shared_aperture_limit() >> 32); // SRC_SHARED_LIMIT
  if (ev == 237)
    return static_cast<uint32_t>(wf.private_aperture_base() >> 32); // SRC_PRIVATE_BASE
  if (ev == 238)
    return static_cast<uint32_t>(wf.private_aperture_limit() >> 32); // SRC_PRIVATE_LIMIT
  if (ev == 249)
    return 0u; // SRC_POPS_EXITING_WAVE_ID (not used in compute)
  if (ev == 250)
    return 0u; // NULL
  if (ev == 251)
    return wf.vcc() == 0 ? 1u : 0u; // VCCZ
  if (ev == 252)
    return wf.exec() == 0 ? 1u : 0u; // EXECZ
  if (ev == 253)
    return wf.read_scc() ? 1u : 0u; // SCC
  throw std::logic_error("Unsupported encoding value for scalar read: " + std::to_string(ev));
}

// Must stay in sync with resolve_src_scalar above — returns true for
// exactly the encoding values that resolve_src_scalar handles without
// throwing. Used by Isa::simd_capable_value() to keep the SIMD fast
// path off operands whose scalar broadcast would throw at runtime.
bool can_resolve_src_scalar(int ev) {
  return (ev >= 0 && ev <= 107) || (ev >= 108 && ev <= 123) || ev == 124 || ev == 126 ||
         ev == 127 || (ev >= 128 && ev <= 208) || (ev >= 235 && ev <= 238) ||
         (ev >= 240 && ev <= 253);
}

uint64_t resolve_src_scalar64(const amdgpu::Wavefront &wf, int ev) {
  if (ev == 102)
    return wf.scratch_base();
  if (ev <= 105) {
    uint32_t lo = wf.cu().read_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev));
    uint32_t hi = wf.cu().read_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev + 1));
    return static_cast<uint64_t>(hi) << 32 | lo;
  }
  if (ev == 106)
    return wf.vcc();
  if (ev >= 108 && ev <= 122) {
    uint32_t lo = wf.cu().read_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev));
    uint32_t hi = wf.cu().read_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev + 1));
    return static_cast<uint64_t>(hi) << 32 | lo;
  }
  if (ev == 124)
    return wf.m0();
  if (ev == 126)
    return wf.exec();
  if (ev >= 128 && ev <= 192)
    return static_cast<uint64_t>(ev - 128);
  if (ev >= 193 && ev <= 208)
    return static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(-(ev - 192))));
  if (ev == 230)
    return wf.scratch_base(); // SRC_FLAT_SCRATCH_BASE
  if (ev == 240)
    return 0x3FE0000000000000ULL; // 0.5
  if (ev == 241)
    return 0xBFE0000000000000ULL; // -0.5
  if (ev == 242)
    return 0x3FF0000000000000ULL; // 1.0
  if (ev == 243)
    return 0xBFF0000000000000ULL; // -1.0
  if (ev == 244)
    return 0x4000000000000000ULL; // 2.0
  if (ev == 245)
    return 0xC000000000000000ULL; // -2.0
  if (ev == 246)
    return 0x4010000000000000ULL; // 4.0
  if (ev == 247)
    return 0xC010000000000000ULL; // -4.0
  if (ev == 248)
    return 0x3FC45F306DC9C883ULL; // 1/(2*pi)
  if (ev == 235)
    return wf.shared_aperture_base(); // SRC_SHARED_BASE
  if (ev == 236)
    return wf.shared_aperture_limit(); // SRC_SHARED_LIMIT
  if (ev == 237)
    return wf.private_aperture_base(); // SRC_PRIVATE_BASE
  if (ev == 238)
    return wf.private_aperture_limit(); // SRC_PRIVATE_LIMIT
  throw std::logic_error("Unsupported encoding value for scalar64 read: " + std::to_string(ev));
}

void resolve_dst_write(amdgpu::Wavefront &wf, int ev, uint32_t val) {
  if (ev == 102) {
    uint64_t sb = wf.scratch_base();
    wf.set_scratch_base((sb & 0xFFFFFFFF00000000ULL) | val);
    return;
  }
  if (ev == 103) {
    uint64_t sb = wf.scratch_base();
    wf.set_scratch_base((sb & 0x00000000FFFFFFFFULL) | (static_cast<uint64_t>(val) << 32));
    return;
  }
  if (ev <= 105) {
    wf.cu().write_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev), val);
    return;
  }
  if (ev == 106) {
    wf.set_vcc((wf.vcc() & 0xFFFFFFFF00000000ULL) | val);
    return;
  }
  if (ev == 107) {
    wf.set_vcc((wf.vcc() & 0x00000000FFFFFFFFULL) | (static_cast<uint64_t>(val) << 32));
    return;
  }
  if (ev >= 108 && ev <= 123) {
    wf.cu().write_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev), val);
    return;
  }
  if (ev == 124) {
    wf.set_m0(val);
    return;
  }
  if (ev == 126) {
    wf.set_exec((wf.exec() & 0xFFFFFFFF00000000ULL) | val);
    return;
  }
  if (ev == 127) {
    wf.set_exec((wf.exec() & 0x00000000FFFFFFFFULL) | (static_cast<uint64_t>(val) << 32));
    return;
  }
  throw std::logic_error("Unsupported encoding value for scalar write: " + std::to_string(ev));
}

void resolve_dst_write64(amdgpu::Wavefront &wf, int ev, uint64_t val) {
  if (ev == 102) {
    wf.set_scratch_base(val);
    return;
  }
  if (ev <= 105) {
    wf.cu().write_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev),
                       static_cast<uint32_t>(val));
    wf.cu().write_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev + 1),
                       static_cast<uint32_t>(val >> 32));
    return;
  }
  if (ev == 106) {
    wf.set_vcc(val);
    return;
  }
  if (ev >= 108 && ev <= 122) {
    wf.cu().write_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev),
                       static_cast<uint32_t>(val));
    wf.cu().write_sgpr(wf.sgpr_alloc().base + static_cast<uint32_t>(ev + 1),
                       static_cast<uint32_t>(val >> 32));
    return;
  }
  if (ev == 124)
    return;
  if (ev == 126) {
    wf.set_exec(val);
    return;
  }
  throw std::logic_error("Unsupported encoding value for scalar64 write: " + std::to_string(ev));
}

bool is_vgpr_only_type(OperandType t) {
  return t == OperandType::OPR_VGPR || t == OperandType::OPR_SRC_VGPR;
}

bool is_immediate_type(OperandType t) {
  return t == OperandType::OPR_SIMM16 || t == OperandType::OPR_SIMM32 ||
         t == OperandType::OPR_SIMM8 || t == OperandType::OPR_LABEL ||
         t == OperandType::OPR_WAITCNT;
}

uint32_t vgpr_index(OperandType opr_type, int ev) {
  if (opr_type == OperandType::OPR_VGPR)
    return static_cast<uint32_t>(ev);
  return static_cast<uint32_t>(ev - 256);
}

} // namespace

// Isa::-scoped SIMD traits — see rocjitsu/isa/isa_operand_simd_inl.h
// for the templated callers in AmdgpuIsaOperand<Isa>.
std::optional<uint32_t> Isa::resolved_vgpr_offset(OperandType opr_type, int ev) {
  if (is_vgpr_only_type(opr_type))
    return vgpr_index(opr_type, ev);
  if (is_immediate_type(opr_type))
    return std::nullopt;
  if (ev >= 256 && ev <= 511)
    return static_cast<uint32_t>(ev - 256);
  return std::nullopt;
}

bool Isa::simd_capable_value(OperandType opr_type, int ev) {
  return resolved_vgpr_offset(opr_type, ev).has_value() || is_immediate_type(opr_type) ||
         can_resolve_src_scalar(ev);
}

uint32_t Isa::simd_broadcast_value(const amdgpu::Wavefront &wf, OperandType opr_type, int ev) {
  return is_immediate_type(opr_type) ? static_cast<uint32_t>(ev) : resolve_src_scalar(wf, ev);
}

uint32_t Operand::read_scalar(const amdgpu::Wavefront &wf) const {
  if (delegate())
    return delegate()->read_scalar(wf);
  if (has_literal64_)
    return static_cast<uint32_t>(literal64_value_);
  if (is_immediate_type(opr_type_))
    return static_cast<uint32_t>(encoding_value_);
  return resolve_src_scalar(wf, encoding_value_);
}

uint32_t Operand::read_lane(const amdgpu::Wavefront &wf, uint32_t lane) const {
  if (delegate())
    return delegate()->read_lane(wf, lane);
  int ev = encoding_value_;
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, ev)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    return wf.cu().read_vgpr(wf.vgpr_alloc().base + voff, lane);
  }
  if (is_immediate_type(opr_type_))
    return static_cast<uint32_t>(ev);
  return resolve_src_scalar(wf, ev);
}

void Operand::write_scalar(amdgpu::Wavefront &wf, uint32_t val) const {
  resolve_dst_write(wf, encoding_value_, val);
}

void Operand::write_lane(amdgpu::Wavefront &wf, uint32_t lane, uint32_t val) const {
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, encoding_value_)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    wf.cu().write_vgpr(wf.vgpr_alloc().base + voff, lane, val);
    return;
  }
  throw std::logic_error("write_lane called on non-VGPR operand type");
}

uint64_t Operand::read_lane64(const amdgpu::Wavefront &wf, uint32_t lane) const {
  if (delegate())
    return delegate()->read_lane64(wf, lane);
  int ev = encoding_value_;
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, ev)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    uint32_t lo = wf.cu().read_vgpr(idx, lane);
    uint32_t hi = wf.cu().read_vgpr(idx + 1, lane);
    return static_cast<uint64_t>(hi) << 32 | lo;
  }
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(ev)));
  return resolve_src_scalar64(wf, ev);
}

void Operand::write_lane64(amdgpu::Wavefront &wf, uint32_t lane, uint64_t val) const {
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, encoding_value_)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    wf.cu().write_vgpr(idx, lane, static_cast<uint32_t>(val));
    wf.cu().write_vgpr(idx + 1, lane, static_cast<uint32_t>(val >> 32));
    return;
  }
  throw std::logic_error("write_lane64 called on non-VGPR operand type");
}

uint64_t Operand::read_scalar64(const amdgpu::Wavefront &wf) const {
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(encoding_value_)));
  return resolve_src_scalar64(wf, encoding_value_);
}

void Operand::write_scalar64(amdgpu::Wavefront &wf, uint64_t val) const {
  resolve_dst_write64(wf, encoding_value_, val);
}

} // namespace rdna3_5
} // namespace rocjitsu
