type = "cli"
title = "compile HIP source to HIP fatbin with AMD Clang"
binary = "amdclang++"
args = [
    "-x", "hip",
    "--offload-arch=${arch}",
    "--rocm-path=<rocm>",
    "-fPIC",
    "-c",
    "-O2",
    "-o", "${out}",
    "${src}"
]

[output]
type = "hip_fatbin"

[input.src]
type = "hip_src"

[input.arch]
type = "offload_arch"
