// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_OPERAND_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_OPERAND_H_

#include "rocjitsu/isa/arch/amdgpu/rdna4/isa.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/operand_types.h"
#include "rocjitsu/isa/operand.h"
#include <string>

namespace rocjitsu {
namespace rdna4 {

class Operand : public AmdgpuIsaOperand<Isa> {
public:
  Operand(int size_bits, OperandType opr_type, int encoding_value);
  Operand(int size_bits, OperandType opr_type, uint64_t literal64_value, bool is_literal64);
  std::string name() const override;
  std::optional<uint64_t> literal64_value() const override;
  std::optional<RegisterRef> to_register_ref() const override;
  uint32_t read_scalar(const amdgpu::Wavefront &wf) const override;
  uint32_t read_lane(const amdgpu::Wavefront &wf, uint32_t lane) const override;
  void write_scalar(amdgpu::Wavefront &wf, uint32_t val) const override;
  void write_lane(amdgpu::Wavefront &wf, uint32_t lane, uint32_t val) const override;
  uint64_t read_lane64(const amdgpu::Wavefront &wf, uint32_t lane) const override;
  void write_lane64(amdgpu::Wavefront &wf, uint32_t lane, uint64_t val) const override;
  uint64_t read_scalar64(const amdgpu::Wavefront &wf) const override;
  void write_scalar64(amdgpu::Wavefront &wf, uint64_t val) const override;

private:
  uint64_t literal64_value_ = 0;
  bool has_literal64_ = false;
};

} // namespace rdna4
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_OPERAND_H_
