// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna4/vimage.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna4 {

ImageLoadVimage::ImageLoadVimage(const MachineInst *inst)
    : Vimage("image_load", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageLoadVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageLoadVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image load stub — not yet implemented.
  (void)wf;
}

ImageLoadMipVimage::ImageLoadMipVimage(const MachineInst *inst)
    : Vimage("image_load_mip", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageLoadMipVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageLoadMipVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image load stub — not yet implemented.
  (void)wf;
}

ImageLoadPckVimage::ImageLoadPckVimage(const MachineInst *inst)
    : Vimage("image_load_pck", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageLoadPckVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageLoadPckVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image load stub — not yet implemented.
  (void)wf;
}

ImageLoadPckSgnVimage::ImageLoadPckSgnVimage(const MachineInst *inst)
    : Vimage("image_load_pck_sgn", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageLoadPckSgnVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageLoadPckSgnVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image load stub — not yet implemented.
  (void)wf;
}

ImageLoadMipPckVimage::ImageLoadMipPckVimage(const MachineInst *inst)
    : Vimage("image_load_mip_pck", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageLoadMipPckVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageLoadMipPckVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image load stub — not yet implemented.
  (void)wf;
}

ImageLoadMipPckSgnVimage::ImageLoadMipPckSgnVimage(const MachineInst *inst)
    : Vimage("image_load_mip_pck_sgn", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageLoadMipPckSgnVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageLoadMipPckSgnVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image load stub — not yet implemented.
  (void)wf;
}

ImageStoreVimage::ImageStoreVimage(const MachineInst *inst)
    : Vimage("image_store", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageStoreVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 0;
}

void ImageStoreVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image store stub — not yet implemented.
  (void)wf;
}

ImageStoreMipVimage::ImageStoreMipVimage(const MachineInst *inst)
    : Vimage("image_store_mip", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageStoreMipVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 0;
}

void ImageStoreMipVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image store stub — not yet implemented.
  (void)wf;
}

ImageStorePckVimage::ImageStorePckVimage(const MachineInst *inst)
    : Vimage("image_store_pck", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageStorePckVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 0;
}

void ImageStorePckVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image store stub — not yet implemented.
  (void)wf;
}

ImageStoreMipPckVimage::ImageStoreMipPckVimage(const MachineInst *inst)
    : Vimage("image_store_mip_pck", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageStoreMipPckVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 0;
}

void ImageStoreMipPckVimage::execute_impl(amdgpu::Wavefront &wf) {
  // Minimal image store stub — not yet implemented.
  (void)wf;
}

ImageAtomicSwapVimage::ImageAtomicSwapVimage(const MachineInst *inst)
    : Vimage("image_atomic_swap", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicSwapVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicSwapVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicCmpswapVimage::ImageAtomicCmpswapVimage(const MachineInst *inst)
    : Vimage("image_atomic_cmpswap", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicCmpswapVimage>()),
      vdata(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicCmpswapVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicAddUintVimage::ImageAtomicAddUintVimage(const MachineInst *inst)
    : Vimage("image_atomic_add_uint", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicAddUintVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicAddUintVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicSubUintVimage::ImageAtomicSubUintVimage(const MachineInst *inst)
    : Vimage("image_atomic_sub_uint", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicSubUintVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicSubUintVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicMinIntVimage::ImageAtomicMinIntVimage(const MachineInst *inst)
    : Vimage("image_atomic_min_int", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicMinIntVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicMinIntVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicMinUintVimage::ImageAtomicMinUintVimage(const MachineInst *inst)
    : Vimage("image_atomic_min_uint", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicMinUintVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicMinUintVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicMaxIntVimage::ImageAtomicMaxIntVimage(const MachineInst *inst)
    : Vimage("image_atomic_max_int", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicMaxIntVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicMaxIntVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicMaxUintVimage::ImageAtomicMaxUintVimage(const MachineInst *inst)
    : Vimage("image_atomic_max_uint", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicMaxUintVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicMaxUintVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicAndVimage::ImageAtomicAndVimage(const MachineInst *inst)
    : Vimage("image_atomic_and", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicAndVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicAndVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicOrVimage::ImageAtomicOrVimage(const MachineInst *inst)
    : Vimage("image_atomic_or", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicOrVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicOrVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicXorVimage::ImageAtomicXorVimage(const MachineInst *inst)
    : Vimage("image_atomic_xor", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicXorVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicXorVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicIncUintVimage::ImageAtomicIncUintVimage(const MachineInst *inst)
    : Vimage("image_atomic_inc_uint", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicIncUintVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicIncUintVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicDecUintVimage::ImageAtomicDecUintVimage(const MachineInst *inst)
    : Vimage("image_atomic_dec_uint", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicDecUintVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicDecUintVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageGetResinfoVimage::ImageGetResinfoVimage(const MachineInst *inst)
    : Vimage("image_get_resinfo", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageGetResinfoVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageGetResinfoVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageBvhIntersectRayVimage::ImageBvhIntersectRayVimage(const MachineInst *inst)
    : Vimage("image_bvh_intersect_ray", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageBvhIntersectRayVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(128, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageBvhIntersectRayVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageBvh64IntersectRayVimage::ImageBvh64IntersectRayVimage(const MachineInst *inst)
    : Vimage("image_bvh64_intersect_ray", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageBvh64IntersectRayVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(128, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageBvh64IntersectRayVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

ImageBvhDualIntersectRayVimage::ImageBvhDualIntersectRayVimage(const MachineInst *inst)
    : Vimage("image_bvh_dual_intersect_ray", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageBvhDualIntersectRayVimage>()),
      vdata(320, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(128, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageBvhDualIntersectRayVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

ImageBvh8IntersectRayVimage::ImageBvh8IntersectRayVimage(const MachineInst *inst)
    : Vimage("image_bvh8_intersect_ray", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageBvh8IntersectRayVimage>()),
      vdata(320, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(128, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  dst_operands_[0] = &vdata;
  src_operands_[0] = &rsrc;
  num_src_ = 1;
  num_dst_ = 1;
}

void ImageBvh8IntersectRayVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf;
  throw util::UnimplementedInst(mnemonic());
}

ImageAtomicAddFltVimage::ImageAtomicAddFltVimage(const MachineInst *inst)
    : Vimage("image_atomic_add_flt", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicAddFltVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicAddFltVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicMinFltVimage::ImageAtomicMinFltVimage(const MachineInst *inst)
    : Vimage("image_atomic_min_flt", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicMinFltVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicMinFltVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicMaxFltVimage::ImageAtomicMaxFltVimage(const MachineInst *inst)
    : Vimage("image_atomic_max_flt", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicMaxFltVimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicMaxFltVimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicPkAddF16Vimage::ImageAtomicPkAddF16Vimage(const MachineInst *inst)
    : Vimage("image_atomic_pk_add_f16", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicPkAddF16Vimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicPkAddF16Vimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

ImageAtomicPkAddBf16Vimage::ImageAtomicPkAddBf16Vimage(const MachineInst *inst)
    : Vimage("image_atomic_pk_add_bf16", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<ImageAtomicPkAddBf16Vimage>()),
      vdata(128, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdata),
      rsrc(256, OperandType::OPR_SREG, reinterpret_cast<const OpEncoding *>(inst)->rsrc) {
  src_operands_[0] = &vdata;
  dst_operands_[0] = &vdata;
  src_operands_[1] = &rsrc;
  num_src_ = 2;
  num_dst_ = 1;
}

void ImageAtomicPkAddBf16Vimage::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Image pipeline not yet implemented.
}

} // namespace rdna4
} // namespace rocjitsu
