// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VSAMPLE_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VSAMPLE_H_

#include "rocjitsu/isa/arch/amdgpu/rdna4/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/isa.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/operand.h"

namespace rocjitsu {
namespace rdna4 {

class ImageMsaaLoadVsample : public Vsample {
public:
  ImageMsaaLoadVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
};

class ImageSampleVsample : public Vsample {
public:
  ImageSampleVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDVsample : public Vsample {
public:
  ImageSampleDVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleLVsample : public Vsample {
public:
  ImageSampleLVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleBVsample : public Vsample {
public:
  ImageSampleBVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleLzVsample : public Vsample {
public:
  ImageSampleLzVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCVsample : public Vsample {
public:
  ImageSampleCVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDVsample : public Vsample {
public:
  ImageSampleCDVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCLVsample : public Vsample {
public:
  ImageSampleCLVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCBVsample : public Vsample {
public:
  ImageSampleCBVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCLzVsample : public Vsample {
public:
  ImageSampleCLzVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleOVsample : public Vsample {
public:
  ImageSampleOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDOVsample : public Vsample {
public:
  ImageSampleDOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleLOVsample : public Vsample {
public:
  ImageSampleLOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleBOVsample : public Vsample {
public:
  ImageSampleBOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleLzOVsample : public Vsample {
public:
  ImageSampleLzOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCOVsample : public Vsample {
public:
  ImageSampleCOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDOVsample : public Vsample {
public:
  ImageSampleCDOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCLOVsample : public Vsample {
public:
  ImageSampleCLOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCBOVsample : public Vsample {
public:
  ImageSampleCBOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCLzOVsample : public Vsample {
public:
  ImageSampleCLzOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4Vsample : public Vsample {
public:
  ImageGather4Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4LVsample : public Vsample {
public:
  ImageGather4LVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4BVsample : public Vsample {
public:
  ImageGather4BVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4LzVsample : public Vsample {
public:
  ImageGather4LzVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CVsample : public Vsample {
public:
  ImageGather4CVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CLzVsample : public Vsample {
public:
  ImageGather4CLzVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4OVsample : public Vsample {
public:
  ImageGather4OVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4LzOVsample : public Vsample {
public:
  ImageGather4LzOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CLzOVsample : public Vsample {
public:
  ImageGather4CLzOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGetLodVsample : public Vsample {
public:
  ImageGetLodVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDG16Vsample : public Vsample {
public:
  ImageSampleDG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDG16Vsample : public Vsample {
public:
  ImageSampleCDG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDOG16Vsample : public Vsample {
public:
  ImageSampleDOG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDOG16Vsample : public Vsample {
public:
  ImageSampleCDOG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleClVsample : public Vsample {
public:
  ImageSampleClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDClVsample : public Vsample {
public:
  ImageSampleDClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleBClVsample : public Vsample {
public:
  ImageSampleBClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCClVsample : public Vsample {
public:
  ImageSampleCClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDClVsample : public Vsample {
public:
  ImageSampleCDClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCBClVsample : public Vsample {
public:
  ImageSampleCBClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleClOVsample : public Vsample {
public:
  ImageSampleClOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDClOVsample : public Vsample {
public:
  ImageSampleDClOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleBClOVsample : public Vsample {
public:
  ImageSampleBClOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCClOVsample : public Vsample {
public:
  ImageSampleCClOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDClOVsample : public Vsample {
public:
  ImageSampleCDClOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCBClOVsample : public Vsample {
public:
  ImageSampleCBClOVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDClG16Vsample : public Vsample {
public:
  ImageSampleCDClG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDClOG16Vsample : public Vsample {
public:
  ImageSampleDClOG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleCDClOG16Vsample : public Vsample {
public:
  ImageSampleCDClOG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageSampleDClG16Vsample : public Vsample {
public:
  ImageSampleDClG16Vsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4ClVsample : public Vsample {
public:
  ImageGather4ClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4BClVsample : public Vsample {
public:
  ImageGather4BClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CClVsample : public Vsample {
public:
  ImageGather4CClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CLVsample : public Vsample {
public:
  ImageGather4CLVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CBVsample : public Vsample {
public:
  ImageGather4CBVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4CBClVsample : public Vsample {
public:
  ImageGather4CBClVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

class ImageGather4hVsample : public Vsample {
public:
  ImageGather4hVsample(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdata;
  Operand rsrc;
  Operand samp;
};

} // namespace rdna4
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VSAMPLE_H_
