// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna2/vintrp.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna2 {

VInterpP1F32Vintrp::VInterpP1F32Vintrp(const MachineInst *inst)
    : Vintrp("v_interp_p1_f32", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<VInterpP1F32Vintrp>()),
      vdst(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdst),
      vsrc(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc),
      attr(32, OperandType::OPR_ATTR, reinterpret_cast<const OpEncoding *>(inst)->attr) {
  dst_operands_[0] = &vdst;
  src_operands_[0] = &vsrc;
  src_operands_[1] = &attr;
  num_src_ = 2;
  num_dst_ = 1;
}

void VInterpP1F32Vintrp::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Interpolation/LDS-direct: no-op in compute simulation.
}

VInterpP2F32Vintrp::VInterpP2F32Vintrp(const MachineInst *inst)
    : Vintrp("v_interp_p2_f32", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<VInterpP2F32Vintrp>()),
      vdst(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdst),
      vsrc(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vsrc),
      attr(32, OperandType::OPR_ATTR, reinterpret_cast<const OpEncoding *>(inst)->attr) {
  src_operands_[0] = &vdst;
  dst_operands_[0] = &vdst;
  src_operands_[1] = &vsrc;
  src_operands_[2] = &attr;
  num_src_ = 3;
  num_dst_ = 1;
}

void VInterpP2F32Vintrp::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Interpolation/LDS-direct: no-op in compute simulation.
}

VInterpMovF32Vintrp::VInterpMovF32Vintrp(const MachineInst *inst)
    : Vintrp("v_interp_mov_f32", reinterpret_cast<const OpEncoding *>(inst),
             make_exec_fn<VInterpMovF32Vintrp>()),
      vdst(32, OperandType::OPR_VGPR, reinterpret_cast<const OpEncoding *>(inst)->vdst),
      vsrc(32, OperandType::OPR_PARAM, reinterpret_cast<const OpEncoding *>(inst)->vsrc),
      attr(32, OperandType::OPR_ATTR, reinterpret_cast<const OpEncoding *>(inst)->attr) {
  dst_operands_[0] = &vdst;
  src_operands_[0] = &vsrc;
  src_operands_[1] = &attr;
  num_src_ = 2;
  num_dst_ = 1;
}

void VInterpMovF32Vintrp::execute_impl(amdgpu::Wavefront &wf) {
  (void)wf; // Interpolation/LDS-direct: no-op in compute simulation.
}

} // namespace rdna2
} // namespace rocjitsu
