# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: projects/hipfile/docs/conf.py

formats: []

python:
  install:
    - requirements: projects/hipfile/docs/sphinx/requirements.in

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
