// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/cdna4/operand.h"
#include "rocjitsu/isa/arch/amdgpu/shared/scalar_operand_resolve.h"
#include "rocjitsu/isa/isa_operand_simd_inl.h"
#include "rocjitsu/vm/amdgpu/compute_unit.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include <format>
#include <optional>
#include <stdexcept>
#include <string>

namespace rocjitsu {
namespace cdna4 {

namespace {
std::string reg_name(const char *prefix, int reg_num, int size_bits) {
  int count = size_bits / 32;
  if (count <= 1)
    return prefix + std::to_string(reg_num);
  return std::string(prefix) + "[" + std::to_string(reg_num) + ":" +
         std::to_string(reg_num + count - 1) + "]";
}
} // namespace

Operand::Operand(int size_bits, OperandType opr_type, int encoding_value)
    : AmdgpuIsaOperand<Isa>(size_bits, opr_type, encoding_value) {
  is_vgpr_ = is_vgpr_operand_type(opr_type);
}

Operand::Operand(int size_bits, OperandType opr_type, int encoding_value,
                 uint16_t literal16_display_value, bool has_literal16_display)
    : AmdgpuIsaOperand<Isa>(size_bits, opr_type, encoding_value),
      literal16_display_value_(literal16_display_value),
      has_literal16_display_(has_literal16_display) {
  is_vgpr_ = is_vgpr_operand_type(opr_type);
}

Operand::Operand(int size_bits, OperandType opr_type, uint64_t literal64_value, bool is_literal64)
    : AmdgpuIsaOperand<Isa>(size_bits, opr_type, static_cast<int>(literal64_value)),
      literal64_value_(literal64_value), has_literal64_(is_literal64) {
  is_vgpr_ = is_vgpr_operand_type(opr_type);
}

std::optional<uint64_t> Operand::literal64_value() const {
  if (!has_literal64_)
    return std::nullopt;
  return literal64_value_;
}

std::string Operand::name() const {
  if (has_literal64_)
    return std::format("0x{:x}", literal64_value_);
  if (has_literal16_display_)
    return std::format("0x{:x}", literal16_display_value_);
  switch (opr_type_) {
  case OperandType::OPR_ACCVGPR: {
    if (encoding_value_ >= OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelAccvgpr::OPR_ACCVGPR_ACC_MAX)
      return reg_name("acc", encoding_value_ - OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_DSMEM: {
    if (encoding_value_ == OpSelDsmem::OPR_DSMEM_DSMEM)
      return "dsmem";
    break;
  }
  case OperandType::OPR_FLAT_SCRATCH: {
    if (encoding_value_ == OpSelFlatScratch::OPR_FLAT_SCRATCH_FLAT_SCRATCH_ALL)
      return "FLAT_SCRATCH_ALL";
    break;
  }
  case OperandType::OPR_GPUMEM: {
    if (encoding_value_ == OpSelGpumem::OPR_GPUMEM_GPUMEM)
      return "gpumem";
    break;
  }
  case OperandType::OPR_PC: {
    if (encoding_value_ == OpSelPc::OPR_PC_PC_ALL)
      return "PC_ALL";
    break;
  }
  case OperandType::OPR_SDST: {
    if (encoding_value_ >= OpSelSdst::OPR_SDST_SGPR_MIN &&
        encoding_value_ <= OpSelSdst::OPR_SDST_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSdst::OPR_SDST_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSdst::OPR_SDST_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSdst::OPR_SDST_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSdst::OPR_SDST_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSdst::OPR_SDST_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSdst::OPR_SDST_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSdst::OPR_SDST_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSdst::OPR_SDST_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSdst::OPR_SDST_M0)
      return "M0";
    if (encoding_value_ == OpSelSdst::OPR_SDST_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSdst::OPR_SDST_EXEC_HI)
      return "EXEC_HI";
    break;
  }
  case OperandType::OPR_SDST_EXEC: {
    if (encoding_value_ == OpSelSdstExec::OPR_SDST_EXEC_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSdstExec::OPR_SDST_EXEC_EXEC_HI)
      return "EXEC_HI";
    break;
  }
  case OperandType::OPR_SDST_M0: {
    if (encoding_value_ == OpSelSdstM0::OPR_SDST_M0_M0)
      return "M0";
    break;
  }
  case OperandType::OPR_SMEM_OFFSET: {
    if (encoding_value_ >= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN &&
        encoding_value_ <= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSmemOffset::OPR_SMEM_OFFSET_M0)
      return "M0";
    break;
  }
  case OperandType::OPR_SRC: {
    if (encoding_value_ >= OpSelSrc::OPR_SRC_SGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSrc::OPR_SRC_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrc::OPR_SRC_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSrc::OPR_SRC_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSrc::OPR_SRC_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSrc::OPR_SRC_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSrc::OPR_SRC_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSrc::OPR_SRC_M0)
      return "M0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSrc::OPR_SRC_EXEC_HI)
      return "EXEC_HI";
    if (encoding_value_ >= OpSelSrc::OPR_SRC_POS_INT_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSrc::OPR_SRC_POS_INT_MIN);
    if (encoding_value_ >= OpSelSrc::OPR_SRC_NEG_INT_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSrc::OPR_SRC_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSrc::OPR_SRC_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_VCCZ)
      return "SRC_VCCZ";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_EXECZ)
      return "SRC_EXECZ";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_SCC)
      return "SRC_SCC";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_SHARED_BASE)
      return "SRC_SHARED_BASE";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_SHARED_LIMIT)
      return "SRC_SHARED_LIMIT";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_PRIVATE_BASE)
      return "SRC_PRIVATE_BASE";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_PRIVATE_LIMIT)
      return "SRC_PRIVATE_LIMIT";
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_POPS_EXITING_WAVE_ID)
      return "SRC_POPS_EXITING_WAVE_ID";
    if (encoding_value_ >= OpSelSrc::OPR_SRC_VGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrc::OPR_SRC_VGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrc::OPR_SRC_SRC_LITERAL)
      return "literal";
    break;
  }
  case OperandType::OPR_SRC_ACCVGPR: {
    if (encoding_value_ >= OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MAX)
      return reg_name("acc", encoding_value_ - OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MIN,
                      size_bits_);
    break;
  }
  case OperandType::OPR_SRC_NOLDS: {
    if (encoding_value_ >= OpSelSrcNolds::OPR_SRC_NOLDS_SGPR_MIN &&
        encoding_value_ <= OpSelSrcNolds::OPR_SRC_NOLDS_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSrcNolds::OPR_SRC_NOLDS_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_M0)
      return "M0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_EXEC_HI)
      return "EXEC_HI";
    if (encoding_value_ >= OpSelSrcNolds::OPR_SRC_NOLDS_POS_INT_MIN &&
        encoding_value_ <= OpSelSrcNolds::OPR_SRC_NOLDS_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSrcNolds::OPR_SRC_NOLDS_POS_INT_MIN);
    if (encoding_value_ >= OpSelSrcNolds::OPR_SRC_NOLDS_NEG_INT_MIN &&
        encoding_value_ <= OpSelSrcNolds::OPR_SRC_NOLDS_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSrcNolds::OPR_SRC_NOLDS_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_VCCZ)
      return "SRC_VCCZ";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_EXECZ)
      return "SRC_EXECZ";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_SCC)
      return "SRC_SCC";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_SHARED_BASE)
      return "SRC_SHARED_BASE";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_SHARED_LIMIT)
      return "SRC_SHARED_LIMIT";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_PRIVATE_BASE)
      return "SRC_PRIVATE_BASE";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_PRIVATE_LIMIT)
      return "SRC_PRIVATE_LIMIT";
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_POPS_EXITING_WAVE_ID)
      return "SRC_POPS_EXITING_WAVE_ID";
    if (encoding_value_ >= OpSelSrcNolds::OPR_SRC_NOLDS_VGPR_MIN &&
        encoding_value_ <= OpSelSrcNolds::OPR_SRC_NOLDS_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrcNolds::OPR_SRC_NOLDS_VGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_SRC_LITERAL)
      return "literal";
    break;
  }
  case OperandType::OPR_SRC_NOLIT: {
    if (encoding_value_ >= OpSelSrcNolit::OPR_SRC_NOLIT_SGPR_MIN &&
        encoding_value_ <= OpSelSrcNolit::OPR_SRC_NOLIT_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSrcNolit::OPR_SRC_NOLIT_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_M0)
      return "M0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_EXEC_HI)
      return "EXEC_HI";
    if (encoding_value_ >= OpSelSrcNolit::OPR_SRC_NOLIT_POS_INT_MIN &&
        encoding_value_ <= OpSelSrcNolit::OPR_SRC_NOLIT_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSrcNolit::OPR_SRC_NOLIT_POS_INT_MIN);
    if (encoding_value_ >= OpSelSrcNolit::OPR_SRC_NOLIT_NEG_INT_MIN &&
        encoding_value_ <= OpSelSrcNolit::OPR_SRC_NOLIT_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSrcNolit::OPR_SRC_NOLIT_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_VCCZ)
      return "SRC_VCCZ";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_EXECZ)
      return "SRC_EXECZ";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_SCC)
      return "SRC_SCC";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_SHARED_BASE)
      return "SRC_SHARED_BASE";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_SHARED_LIMIT)
      return "SRC_SHARED_LIMIT";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_PRIVATE_BASE)
      return "SRC_PRIVATE_BASE";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_PRIVATE_LIMIT)
      return "SRC_PRIVATE_LIMIT";
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_SRC_POPS_EXITING_WAVE_ID)
      return "SRC_POPS_EXITING_WAVE_ID";
    if (encoding_value_ >= OpSelSrcNolit::OPR_SRC_NOLIT_VGPR_MIN &&
        encoding_value_ <= OpSelSrcNolit::OPR_SRC_NOLIT_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrcNolit::OPR_SRC_NOLIT_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_SRC_SIMPLE: {
    if (encoding_value_ >= OpSelSrcSimple::OPR_SRC_SIMPLE_SGPR_MIN &&
        encoding_value_ <= OpSelSrcSimple::OPR_SRC_SIMPLE_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSrcSimple::OPR_SRC_SIMPLE_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_M0)
      return "M0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_EXEC_HI)
      return "EXEC_HI";
    if (encoding_value_ >= OpSelSrcSimple::OPR_SRC_SIMPLE_POS_INT_MIN &&
        encoding_value_ <= OpSelSrcSimple::OPR_SRC_SIMPLE_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSrcSimple::OPR_SRC_SIMPLE_POS_INT_MIN);
    if (encoding_value_ >= OpSelSrcSimple::OPR_SRC_SIMPLE_NEG_INT_MIN &&
        encoding_value_ <= OpSelSrcSimple::OPR_SRC_SIMPLE_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSrcSimple::OPR_SRC_SIMPLE_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_VCCZ)
      return "SRC_VCCZ";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_EXECZ)
      return "SRC_EXECZ";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_SCC)
      return "SRC_SCC";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_SHARED_BASE)
      return "SRC_SHARED_BASE";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_SHARED_LIMIT)
      return "SRC_SHARED_LIMIT";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_PRIVATE_BASE)
      return "SRC_PRIVATE_BASE";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_PRIVATE_LIMIT)
      return "SRC_PRIVATE_LIMIT";
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_SRC_POPS_EXITING_WAVE_ID)
      return "SRC_POPS_EXITING_WAVE_ID";
    if (encoding_value_ >= OpSelSrcSimple::OPR_SRC_SIMPLE_VGPR_MIN &&
        encoding_value_ <= OpSelSrcSimple::OPR_SRC_SIMPLE_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrcSimple::OPR_SRC_SIMPLE_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_SRC_VGPR: {
    if (encoding_value_ >= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_SRC_VGPR_OR_ACCVGPR: {
    if (encoding_value_ >= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MAX)
      return reg_name("v",
                      encoding_value_ - OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MIN,
                      size_bits_);
    if (encoding_value_ >= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MAX)
      return reg_name("acc",
                      encoding_value_ - OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MIN,
                      size_bits_);
    break;
  }
  case OperandType::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST: {
    if (encoding_value_ >=
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_VGPR_MAX)
      return reg_name("v",
                      encoding_value_ -
                          OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_VGPR_MIN,
                      size_bits_);
    if (encoding_value_ >= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MAX)
      return reg_name("acc",
                      encoding_value_ -
                          OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MIN,
                      size_bits_);
    if (encoding_value_ >=
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_POS_INT_MIN &&
        encoding_value_ <=
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_POS_INT_MAX)
      return std::to_string(
          encoding_value_ -
          OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_POS_INT_MIN);
    if (encoding_value_ >=
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_NEG_INT_MIN &&
        encoding_value_ <=
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_NEG_INT_MAX)
      return std::to_string(
          -(encoding_value_ -
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_NEG_INT_MIN + 1));
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ ==
        OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    break;
  }
  case OperandType::OPR_SREG: {
    if (encoding_value_ >= OpSelSreg::OPR_SREG_SGPR_MIN &&
        encoding_value_ <= OpSelSreg::OPR_SREG_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSreg::OPR_SREG_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSreg::OPR_SREG_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSreg::OPR_SREG_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSreg::OPR_SREG_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSreg::OPR_SREG_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSreg::OPR_SREG_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSreg::OPR_SREG_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSreg::OPR_SREG_VCC_HI)
      return "VCC_HI";
    break;
  }
  case OperandType::OPR_SREG_NOVCC: {
    if (encoding_value_ >= OpSelSregNovcc::OPR_SREG_NOVCC_SGPR_MIN &&
        encoding_value_ <= OpSelSregNovcc::OPR_SREG_NOVCC_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSregNovcc::OPR_SREG_NOVCC_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSregNovcc::OPR_SREG_NOVCC_TTMP15)
      return "TTMP15";
    break;
  }
  case OperandType::OPR_SSRC: {
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_SGPR_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSsrc::OPR_SSRC_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_M0)
      return "M0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_EXEC_HI)
      return "EXEC_HI";
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_POS_INT_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSsrc::OPR_SSRC_POS_INT_MIN);
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_NEG_INT_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSsrc::OPR_SSRC_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_VCCZ)
      return "SRC_VCCZ";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_EXECZ)
      return "SRC_EXECZ";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_SCC)
      return "SRC_SCC";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_SHARED_BASE)
      return "SRC_SHARED_BASE";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_SHARED_LIMIT)
      return "SRC_SHARED_LIMIT";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_PRIVATE_BASE)
      return "SRC_PRIVATE_BASE";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_PRIVATE_LIMIT)
      return "SRC_PRIVATE_LIMIT";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_POPS_EXITING_WAVE_ID)
      return "SRC_POPS_EXITING_WAVE_ID";
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_SRC_LITERAL)
      return "literal";
    break;
  }
  case OperandType::OPR_SSRC_LANESEL: {
    if (encoding_value_ >= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN &&
        encoding_value_ <= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN,
                      size_bits_);
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSsrcLanesel::OPR_SSRC_LANESEL_M0)
      return "M0";
    break;
  }
  case OperandType::OPR_SSRC_NOLIT: {
    if (encoding_value_ >= OpSelSsrcNolit::OPR_SSRC_NOLIT_SGPR_MIN &&
        encoding_value_ <= OpSelSsrcNolit::OPR_SSRC_NOLIT_SGPR_MAX)
      return reg_name("s", encoding_value_ - OpSelSsrcNolit::OPR_SSRC_NOLIT_SGPR_MIN, size_bits_);
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_XNACK_MASK_LO)
      return "XNACK_MASK_LO";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_XNACK_MASK_HI)
      return "XNACK_MASK_HI";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLAT_SCRATCH_LO)
      return "FLAT_SCRATCH_LO";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLAT_SCRATCH_HI)
      return "FLAT_SCRATCH_HI";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP0)
      return "TTMP0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP1)
      return "TTMP1";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP2)
      return "TTMP2";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP3)
      return "TTMP3";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP4)
      return "TTMP4";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP5)
      return "TTMP5";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP6)
      return "TTMP6";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP7)
      return "TTMP7";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP8)
      return "TTMP8";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP9)
      return "TTMP9";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP10)
      return "TTMP10";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP11)
      return "TTMP11";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP12)
      return "TTMP12";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP13)
      return "TTMP13";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP14)
      return "TTMP14";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_TTMP15)
      return "TTMP15";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_VCC_LO)
      return "VCC_LO";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_VCC_HI)
      return "VCC_HI";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_M0)
      return "M0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_EXEC_LO)
      return "EXEC_LO";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_EXEC_HI)
      return "EXEC_HI";
    if (encoding_value_ >= OpSelSsrcNolit::OPR_SSRC_NOLIT_POS_INT_MIN &&
        encoding_value_ <= OpSelSsrcNolit::OPR_SSRC_NOLIT_POS_INT_MAX)
      return std::to_string(encoding_value_ - OpSelSsrcNolit::OPR_SSRC_NOLIT_POS_INT_MIN);
    if (encoding_value_ >= OpSelSsrcNolit::OPR_SSRC_NOLIT_NEG_INT_MIN &&
        encoding_value_ <= OpSelSsrcNolit::OPR_SSRC_NOLIT_NEG_INT_MAX)
      return std::to_string(-(encoding_value_ - OpSelSsrcNolit::OPR_SSRC_NOLIT_NEG_INT_MIN + 1));
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_HALF)
      return "0.5";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_NEG_HALF)
      return "-0.5";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_ONE)
      return "1.0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_NEG_ONE)
      return "-1.0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_TWO)
      return "2.0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_NEG_TWO)
      return "-2.0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_FOUR)
      return "4.0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_NEG_FOUR)
      return "-4.0";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_FLOAT_ONE_OVER_TWO_PI)
      return "0.15915494";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_VCCZ)
      return "SRC_VCCZ";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_EXECZ)
      return "SRC_EXECZ";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_SCC)
      return "SRC_SCC";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_SHARED_BASE)
      return "SRC_SHARED_BASE";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_SHARED_LIMIT)
      return "SRC_SHARED_LIMIT";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_PRIVATE_BASE)
      return "SRC_PRIVATE_BASE";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_PRIVATE_LIMIT)
      return "SRC_PRIVATE_LIMIT";
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_SRC_POPS_EXITING_WAVE_ID)
      return "SRC_POPS_EXITING_WAVE_ID";
    break;
  }
  case OperandType::OPR_SSRC_SPECIAL_SCC: {
    if (encoding_value_ == OpSelSsrcSpecialScc::OPR_SSRC_SPECIAL_SCC_SRC_SCC)
      return "SRC_SCC";
    break;
  }
  case OperandType::OPR_VCC: {
    if (encoding_value_ == OpSelVcc::OPR_VCC_VCC)
      return "vcc";
    break;
  }
  case OperandType::OPR_VGPR: {
    if (encoding_value_ >= OpSelVgpr::OPR_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelVgpr::OPR_VGPR_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelVgpr::OPR_VGPR_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_VGPR_OR_ACCVGPR: {
    if (encoding_value_ >= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_VGPR_MIN &&
        encoding_value_ <= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_VGPR_MIN,
                      size_bits_);
    if (encoding_value_ >= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_ACC_MAX)
      return reg_name("acc", encoding_value_ - OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_ACC_MIN,
                      size_bits_);
    break;
  }
  case OperandType::OPR_VGPR_OR_LDS: {
    if (encoding_value_ >= OpSelVgprOrLds::OPR_VGPR_OR_LDS_VGPR_MIN &&
        encoding_value_ <= OpSelVgprOrLds::OPR_VGPR_OR_LDS_VGPR_MAX)
      return reg_name("v", encoding_value_ - OpSelVgprOrLds::OPR_VGPR_OR_LDS_VGPR_MIN, size_bits_);
    break;
  }
  case OperandType::OPR_HWREG:
    return std::to_string(encoding_value_);
  case OperandType::OPR_LABEL:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SENDMSG:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SIMM16:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SIMM32:
    return std::format("0x{:x}", static_cast<uint32_t>(encoding_value_));
  case OperandType::OPR_SIMM4:
    return std::to_string(encoding_value_);
  case OperandType::OPR_SIMM8:
    return std::to_string(encoding_value_);
  case OperandType::OPR_WAITCNT: {
    uint32_t vmcnt = (encoding_value_ & 0xF) | (((encoding_value_ >> 14) & 0x3) << 4);
    uint32_t expcnt = (encoding_value_ >> 4) & 0x7;
    uint32_t lgkmcnt = (encoding_value_ >> 8) & 0x0F;
    return std::format("vmcnt({}) expcnt({}) lgkmcnt({})", vmcnt, expcnt, lgkmcnt);
  }
  }
  return std::to_string(encoding_value_);
}

std::optional<RegisterRef> Operand::to_register_ref() const {
  if (size_bits_ == 0)
    return std::nullopt;
  // Liveness tracks operands as contiguous 32-bit register lanes.
  const auto reg_width = static_cast<uint8_t>(size_bits_ > 32 ? size_bits_ / 32 : 1);
  switch (opr_type_) {
  case OperandType::OPR_ACCVGPR: {
    if (encoding_value_ >= OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelAccvgpr::OPR_ACCVGPR_ACC_MAX)
      return RegisterRef{RegClass::ACC_VGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_DSMEM: {
    break;
  }
  case OperandType::OPR_FLAT_SCRATCH: {
    break;
  }
  case OperandType::OPR_GPUMEM: {
    break;
  }
  case OperandType::OPR_PC: {
    break;
  }
  case OperandType::OPR_SDST: {
    if (encoding_value_ >= OpSelSdst::OPR_SDST_SGPR_MIN &&
        encoding_value_ <= OpSelSdst::OPR_SDST_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSdst::OPR_SDST_SGPR_MIN),
                         reg_width};
    if (encoding_value_ == OpSelSdst::OPR_SDST_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSdst::OPR_SDST_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    break;
  }
  case OperandType::OPR_SDST_EXEC: {
    if (encoding_value_ == OpSelSdstExec::OPR_SDST_EXEC_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSdstExec::OPR_SDST_EXEC_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    break;
  }
  case OperandType::OPR_SDST_M0: {
    break;
  }
  case OperandType::OPR_SMEM_OFFSET: {
    if (encoding_value_ >= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN &&
        encoding_value_ <= OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSmemOffset::OPR_SMEM_OFFSET_SGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC: {
    if (encoding_value_ >= OpSelSrc::OPR_SRC_SGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSrc::OPR_SRC_SGPR_MIN),
                         reg_width};
    if (encoding_value_ == OpSelSrc::OPR_SRC_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSrc::OPR_SRC_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    if (encoding_value_ >= OpSelSrc::OPR_SRC_VGPR_MIN &&
        encoding_value_ <= OpSelSrc::OPR_SRC_VGPR_MAX)
      return RegisterRef{RegClass::VGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSrc::OPR_SRC_VGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_SRC_ACCVGPR: {
    if (encoding_value_ >= OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MAX)
      return RegisterRef{
          RegClass::ACC_VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC_NOLDS: {
    if (encoding_value_ >= OpSelSrcNolds::OPR_SRC_NOLDS_SGPR_MIN &&
        encoding_value_ <= OpSelSrcNolds::OPR_SRC_NOLDS_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcNolds::OPR_SRC_NOLDS_SGPR_MIN),
          reg_width};
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSrcNolds::OPR_SRC_NOLDS_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    if (encoding_value_ >= OpSelSrcNolds::OPR_SRC_NOLDS_VGPR_MIN &&
        encoding_value_ <= OpSelSrcNolds::OPR_SRC_NOLDS_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcNolds::OPR_SRC_NOLDS_VGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC_NOLIT: {
    if (encoding_value_ >= OpSelSrcNolit::OPR_SRC_NOLIT_SGPR_MIN &&
        encoding_value_ <= OpSelSrcNolit::OPR_SRC_NOLIT_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcNolit::OPR_SRC_NOLIT_SGPR_MIN),
          reg_width};
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSrcNolit::OPR_SRC_NOLIT_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    if (encoding_value_ >= OpSelSrcNolit::OPR_SRC_NOLIT_VGPR_MIN &&
        encoding_value_ <= OpSelSrcNolit::OPR_SRC_NOLIT_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcNolit::OPR_SRC_NOLIT_VGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC_SIMPLE: {
    if (encoding_value_ >= OpSelSrcSimple::OPR_SRC_SIMPLE_SGPR_MIN &&
        encoding_value_ <= OpSelSrcSimple::OPR_SRC_SIMPLE_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcSimple::OPR_SRC_SIMPLE_SGPR_MIN),
          reg_width};
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSrcSimple::OPR_SRC_SIMPLE_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    if (encoding_value_ >= OpSelSrcSimple::OPR_SRC_SIMPLE_VGPR_MIN &&
        encoding_value_ <= OpSelSrcSimple::OPR_SRC_SIMPLE_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcSimple::OPR_SRC_SIMPLE_VGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC_VGPR: {
    if (encoding_value_ >= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSrcVgpr::OPR_SRC_VGPR_VGPR_MIN), reg_width};
    break;
  }
  case OperandType::OPR_SRC_VGPR_OR_ACCVGPR: {
    if (encoding_value_ >= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ -
                                OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MIN),
          reg_width};
    if (encoding_value_ >= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MAX)
      return RegisterRef{
          RegClass::ACC_VGPR,
          static_cast<uint16_t>(encoding_value_ -
                                OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST: {
    if (encoding_value_ >=
            OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_VGPR_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(
              encoding_value_ -
              OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_VGPR_MIN),
          reg_width};
    if (encoding_value_ >= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MIN &&
        encoding_value_ <= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MAX)
      return RegisterRef{
          RegClass::ACC_VGPR,
          static_cast<uint16_t>(
              encoding_value_ -
              OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SREG: {
    if (encoding_value_ >= OpSelSreg::OPR_SREG_SGPR_MIN &&
        encoding_value_ <= OpSelSreg::OPR_SREG_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSreg::OPR_SREG_SGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_SREG_NOVCC: {
    if (encoding_value_ >= OpSelSregNovcc::OPR_SREG_NOVCC_SGPR_MIN &&
        encoding_value_ <= OpSelSregNovcc::OPR_SREG_NOVCC_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSregNovcc::OPR_SREG_NOVCC_SGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SSRC: {
    if (encoding_value_ >= OpSelSsrc::OPR_SSRC_SGPR_MIN &&
        encoding_value_ <= OpSelSsrc::OPR_SSRC_SGPR_MAX)
      return RegisterRef{RegClass::SGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelSsrc::OPR_SSRC_SGPR_MIN),
                         reg_width};
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSsrc::OPR_SSRC_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    break;
  }
  case OperandType::OPR_SSRC_LANESEL: {
    if (encoding_value_ >= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN &&
        encoding_value_ <= OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSsrcLanesel::OPR_SSRC_LANESEL_SGPR_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_SSRC_NOLIT: {
    if (encoding_value_ >= OpSelSsrcNolit::OPR_SSRC_NOLIT_SGPR_MIN &&
        encoding_value_ <= OpSelSsrcNolit::OPR_SSRC_NOLIT_SGPR_MAX)
      return RegisterRef{
          RegClass::SGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelSsrcNolit::OPR_SSRC_NOLIT_SGPR_MIN),
          reg_width};
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_EXEC_LO)
      return RegisterRef{RegClass::EXEC, 0, reg_width};
    if (encoding_value_ == OpSelSsrcNolit::OPR_SSRC_NOLIT_EXEC_HI)
      return RegisterRef{RegClass::EXEC, 1, reg_width};
    break;
  }
  case OperandType::OPR_SSRC_SPECIAL_SCC: {
    break;
  }
  case OperandType::OPR_VCC: {
    break;
  }
  case OperandType::OPR_VGPR: {
    if (encoding_value_ >= OpSelVgpr::OPR_VGPR_VGPR_MIN &&
        encoding_value_ <= OpSelVgpr::OPR_VGPR_VGPR_MAX)
      return RegisterRef{RegClass::VGPR,
                         static_cast<uint16_t>(encoding_value_ - OpSelVgpr::OPR_VGPR_VGPR_MIN),
                         reg_width};
    break;
  }
  case OperandType::OPR_VGPR_OR_ACCVGPR: {
    if (encoding_value_ >= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_VGPR_MIN &&
        encoding_value_ <= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_VGPR_MIN),
          reg_width};
    if (encoding_value_ >= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_ACC_MIN &&
        encoding_value_ <= OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_ACC_MAX)
      return RegisterRef{
          RegClass::ACC_VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelVgprOrAccvgpr::OPR_VGPR_OR_ACCVGPR_ACC_MIN),
          reg_width};
    break;
  }
  case OperandType::OPR_VGPR_OR_LDS: {
    if (encoding_value_ >= OpSelVgprOrLds::OPR_VGPR_OR_LDS_VGPR_MIN &&
        encoding_value_ <= OpSelVgprOrLds::OPR_VGPR_OR_LDS_VGPR_MAX)
      return RegisterRef{
          RegClass::VGPR,
          static_cast<uint16_t>(encoding_value_ - OpSelVgprOrLds::OPR_VGPR_OR_LDS_VGPR_MIN),
          reg_width};
    break;
  }
  default:
    break;
  }
  return std::nullopt;
}

namespace {

constexpr int kM0EncodingValue = 124;

bool is_vgpr_only_type(OperandType t) {
  return t == OperandType::OPR_VGPR || t == OperandType::OPR_VGPR_OR_ACCVGPR ||
         t == OperandType::OPR_VGPR_OR_LDS || t == OperandType::OPR_SRC_VGPR ||
         t == OperandType::OPR_ACCVGPR || t == OperandType::OPR_SRC_ACCVGPR ||
         t == OperandType::OPR_SRC_VGPR_OR_ACCVGPR;
}

bool is_immediate_type(OperandType t) {
  return t == OperandType::OPR_SIMM16 || t == OperandType::OPR_SIMM32 ||
         t == OperandType::OPR_SIMM4 || t == OperandType::OPR_SIMM8 ||
         t == OperandType::OPR_LABEL || t == OperandType::OPR_WAITCNT;
}

uint32_t vgpr_index(OperandType opr_type, int ev) {
  if (opr_type == OperandType::OPR_VGPR || opr_type == OperandType::OPR_VGPR_OR_ACCVGPR) {
    if (ev >= OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN)
      return 256 + static_cast<uint32_t>(ev - OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN);
    return static_cast<uint32_t>(ev);
  }
  if (opr_type == OperandType::OPR_ACCVGPR) {
    if (ev >= OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN)
      return 256 + static_cast<uint32_t>(ev - OpSelAccvgpr::OPR_ACCVGPR_ACC_MIN);
    return 256 + static_cast<uint32_t>(ev);
  }
  if (opr_type == OperandType::OPR_SRC_ACCVGPR) {
    if (ev >= OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MIN)
      return 256 + static_cast<uint32_t>(ev - OpSelSrcAccvgpr::OPR_SRC_ACCVGPR_ACC_MIN);
    if (ev >= 256)
      return 256 + static_cast<uint32_t>(ev - 256);
    return 256 + static_cast<uint32_t>(ev);
  }
  if (opr_type == OperandType::OPR_SRC_VGPR_OR_ACCVGPR) {
    if (ev >= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MIN)
      return 256 +
             static_cast<uint32_t>(ev - OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_ACC_MIN);
    if (ev >= OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MIN)
      return static_cast<uint32_t>(ev - OpSelSrcVgprOrAccvgpr::OPR_SRC_VGPR_OR_ACCVGPR_VGPR_MIN);
    return static_cast<uint32_t>(ev);
  }
  return static_cast<uint32_t>(ev - 256);
}

uint64_t read_immediate64(OperandType opr_type, int ev) {
  if (opr_type == OperandType::OPR_SIMM32)
    return static_cast<uint64_t>(static_cast<uint32_t>(ev));
  return static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(ev)));
}

} // namespace

// Isa::-scoped SIMD traits — see rocjitsu/isa/isa_operand_simd_inl.h
// for the templated callers in AmdgpuIsaOperand<Isa>.
std::optional<uint32_t> Isa::resolved_vgpr_offset(OperandType opr_type, int ev) {
  if (is_vgpr_only_type(opr_type))
    return vgpr_index(opr_type, ev);
  if (is_immediate_type(opr_type))
    return std::nullopt;
  if (ev >= 256 && ev <= 511)
    return static_cast<uint32_t>(ev - 256);
  if (opr_type == OperandType::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST &&
      ev >= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MIN &&
      ev <= OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MAX) {
    return 256 + static_cast<uint32_t>(
                     ev - OpSelSrcVgprOrAccvgprOrConst::OPR_SRC_VGPR_OR_ACCVGPR_OR_CONST_ACC_MIN);
  }
  return std::nullopt;
}

bool Isa::simd_capable_value(OperandType opr_type, int ev) {
  return resolved_vgpr_offset(opr_type, ev).has_value() || is_immediate_type(opr_type) ||
         amdgpu::can_resolve_src_scalar(ev, kM0EncodingValue);
}

uint32_t Isa::simd_broadcast_value(const amdgpu::Wavefront &wf, OperandType opr_type, int ev) {
  return is_immediate_type(opr_type) ? static_cast<uint32_t>(ev)
                                     : amdgpu::resolve_src_scalar(wf, ev, kM0EncodingValue);
}

uint32_t Operand::read_scalar(const amdgpu::Wavefront &wf) const {
  if (delegate())
    return delegate()->read_scalar(wf);
  if (has_literal64_)
    return static_cast<uint32_t>(literal64_value_);
  if (is_immediate_type(opr_type_))
    return static_cast<uint32_t>(encoding_value_);
  return amdgpu::resolve_src_scalar(wf, encoding_value_, kM0EncodingValue);
}

std::optional<uint64_t> Operand::const_value() const {
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return static_cast<uint64_t>(static_cast<uint32_t>(encoding_value_));
  if (to_register_ref())
    return std::nullopt;
  return amdgpu::resolve_src_scalar_statically(encoding_value_);
}

uint32_t Operand::read_lane(const amdgpu::Wavefront &wf, uint32_t lane) const {
  if (delegate())
    return delegate()->read_lane(wf, lane);
  int ev = encoding_value_;
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, ev)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    return wf.cu().read_vgpr(wf.vgpr_alloc().base + voff, lane);
  }
  if (is_immediate_type(opr_type_))
    return static_cast<uint32_t>(ev);
  if (size_bits_ == 16)
    return amdgpu::resolve_src_scalar16(wf, ev, kM0EncodingValue);
  return amdgpu::resolve_src_scalar(wf, ev, kM0EncodingValue);
}

void Operand::write_scalar(amdgpu::Wavefront &wf, uint32_t val) const {
  amdgpu::resolve_dst_write(wf, encoding_value_, val, kM0EncodingValue);
}

void Operand::write_lane(amdgpu::Wavefront &wf, uint32_t lane, uint32_t val) const {
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, encoding_value_)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    wf.cu().write_vgpr(wf.vgpr_alloc().base + voff, lane, val);
    return;
  }
  throw std::logic_error("write_lane called on non-VGPR operand type");
}

uint64_t Operand::read_lane64(const amdgpu::Wavefront &wf, uint32_t lane) const {
  if (delegate())
    return delegate()->read_lane64(wf, lane);
  int ev = encoding_value_;
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, ev)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, false) : *off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    uint32_t lo = wf.cu().read_vgpr(idx, lane);
    uint32_t hi = wf.cu().read_vgpr(idx + 1, lane);
    return static_cast<uint64_t>(hi) << 32 | lo;
  }
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return read_immediate64(opr_type_, ev);
  return amdgpu::resolve_src_scalar64(wf, ev, kM0EncodingValue);
}

void Operand::write_lane64(amdgpu::Wavefront &wf, uint32_t lane, uint64_t val) const {
  if (auto off = Isa::resolved_vgpr_offset(opr_type_, encoding_value_)) {
    uint32_t voff = wf.gpr_idx_en() ? amdgpu::apply_gpr_idx(wf, *off, true) : *off;
    uint32_t idx = wf.vgpr_alloc().base + voff;
    wf.cu().write_vgpr(idx, lane, static_cast<uint32_t>(val));
    wf.cu().write_vgpr(idx + 1, lane, static_cast<uint32_t>(val >> 32));
    return;
  }
  throw std::logic_error("write_lane64 called on non-VGPR operand type");
}

uint64_t Operand::read_scalar64(const amdgpu::Wavefront &wf) const {
  if (has_literal64_)
    return literal64_value_;
  if (is_immediate_type(opr_type_))
    return read_immediate64(opr_type_, encoding_value_);
  return amdgpu::resolve_src_scalar64(wf, encoding_value_, kM0EncodingValue);
}

void Operand::write_scalar64(amdgpu::Wavefront &wf, uint64_t val) const {
  amdgpu::resolve_dst_write64(wf, encoding_value_, val);
}

} // namespace cdna4
} // namespace rocjitsu
