// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VFLAT_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VFLAT_H_

#include "rocjitsu/isa/arch/amdgpu/rdna4/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/isa.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/operand.h"

namespace rocjitsu {
namespace rdna4 {

class FlatLoadU8Vflat : public Vflat {
public:
  FlatLoadU8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadI8Vflat : public Vflat {
public:
  FlatLoadI8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadU16Vflat : public Vflat {
public:
  FlatLoadU16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadI16Vflat : public Vflat {
public:
  FlatLoadI16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadB32Vflat : public Vflat {
public:
  FlatLoadB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadB64Vflat : public Vflat {
public:
  FlatLoadB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadB96Vflat : public Vflat {
public:
  FlatLoadB96Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadB128Vflat : public Vflat {
public:
  FlatLoadB128Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatStoreB8Vflat : public Vflat {
public:
  FlatStoreB8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatStoreB16Vflat : public Vflat {
public:
  FlatStoreB16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatStoreB32Vflat : public Vflat {
public:
  FlatStoreB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatStoreB64Vflat : public Vflat {
public:
  FlatStoreB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatStoreB96Vflat : public Vflat {
public:
  FlatStoreB96Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatStoreB128Vflat : public Vflat {
public:
  FlatStoreB128Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatLoadD16U8Vflat : public Vflat {
public:
  FlatLoadD16U8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadD16I8Vflat : public Vflat {
public:
  FlatLoadD16I8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadD16B16Vflat : public Vflat {
public:
  FlatLoadD16B16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadD16HiU8Vflat : public Vflat {
public:
  FlatLoadD16HiU8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadD16HiI8Vflat : public Vflat {
public:
  FlatLoadD16HiI8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatLoadD16HiB16Vflat : public Vflat {
public:
  FlatLoadD16HiB16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
};

class FlatStoreD16HiB8Vflat : public Vflat {
public:
  FlatStoreD16HiB8Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatStoreD16HiB16Vflat : public Vflat {
public:
  FlatStoreD16HiB16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicSwapB32Vflat : public Vflat {
public:
  FlatAtomicSwapB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicCmpswapB32Vflat : public Vflat {
public:
  FlatAtomicCmpswapB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicAddU32Vflat : public Vflat {
public:
  FlatAtomicAddU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicSubU32Vflat : public Vflat {
public:
  FlatAtomicSubU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicSubClampU32Vflat : public Vflat {
public:
  FlatAtomicSubClampU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMinI32Vflat : public Vflat {
public:
  FlatAtomicMinI32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMinU32Vflat : public Vflat {
public:
  FlatAtomicMinU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMaxI32Vflat : public Vflat {
public:
  FlatAtomicMaxI32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMaxU32Vflat : public Vflat {
public:
  FlatAtomicMaxU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicAndB32Vflat : public Vflat {
public:
  FlatAtomicAndB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicOrB32Vflat : public Vflat {
public:
  FlatAtomicOrB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicXorB32Vflat : public Vflat {
public:
  FlatAtomicXorB32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicIncU32Vflat : public Vflat {
public:
  FlatAtomicIncU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicDecU32Vflat : public Vflat {
public:
  FlatAtomicDecU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicSwapB64Vflat : public Vflat {
public:
  FlatAtomicSwapB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicCmpswapB64Vflat : public Vflat {
public:
  FlatAtomicCmpswapB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicAddU64Vflat : public Vflat {
public:
  FlatAtomicAddU64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicSubU64Vflat : public Vflat {
public:
  FlatAtomicSubU64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMinI64Vflat : public Vflat {
public:
  FlatAtomicMinI64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMinU64Vflat : public Vflat {
public:
  FlatAtomicMinU64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMaxI64Vflat : public Vflat {
public:
  FlatAtomicMaxI64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMaxU64Vflat : public Vflat {
public:
  FlatAtomicMaxU64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicAndB64Vflat : public Vflat {
public:
  FlatAtomicAndB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicOrB64Vflat : public Vflat {
public:
  FlatAtomicOrB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicXorB64Vflat : public Vflat {
public:
  FlatAtomicXorB64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicIncU64Vflat : public Vflat {
public:
  FlatAtomicIncU64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicDecU64Vflat : public Vflat {
public:
  FlatAtomicDecU64Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicCondSubU32Vflat : public Vflat {
public:
  FlatAtomicCondSubU32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMinNumF32Vflat : public Vflat {
public:
  FlatAtomicMinNumF32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicMaxNumF32Vflat : public Vflat {
public:
  FlatAtomicMaxNumF32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicAddF32Vflat : public Vflat {
public:
  FlatAtomicAddF32Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicPkAddF16Vflat : public Vflat {
public:
  FlatAtomicPkAddF16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

class FlatAtomicPkAddBf16Vflat : public Vflat {
public:
  FlatAtomicPkAddBf16Vflat(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand vaddr;
  Operand vsrc;
};

} // namespace rdna4
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VFLAT_H_
