// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#ifndef ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VOP3P_H_
#define ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VOP3P_H_

#include "rocjitsu/isa/arch/amdgpu/rdna4/encodings.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/isa.h"
#include "rocjitsu/isa/arch/amdgpu/rdna4/operand.h"

namespace rocjitsu {
namespace rdna4 {

class VPkMadI16Vop3p : public Vop3p {
public:
  VPkMadI16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VPkMulLoU16Vop3p : public Vop3p {
public:
  VPkMulLoU16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkAddI16Vop3p : public Vop3p {
public:
  VPkAddI16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkSubI16Vop3p : public Vop3p {
public:
  VPkSubI16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkLshlrevB16Vop3p : public Vop3p {
public:
  VPkLshlrevB16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkLshrrevB16Vop3p : public Vop3p {
public:
  VPkLshrrevB16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkAshrrevI16Vop3p : public Vop3p {
public:
  VPkAshrrevI16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMaxI16Vop3p : public Vop3p {
public:
  VPkMaxI16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMinI16Vop3p : public Vop3p {
public:
  VPkMinI16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMadU16Vop3p : public Vop3p {
public:
  VPkMadU16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VPkAddU16Vop3p : public Vop3p {
public:
  VPkAddU16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkSubU16Vop3p : public Vop3p {
public:
  VPkSubU16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMaxU16Vop3p : public Vop3p {
public:
  VPkMaxU16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMinU16Vop3p : public Vop3p {
public:
  VPkMinU16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkFmaF16Vop3p : public Vop3p {
public:
  VPkFmaF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VPkAddF16Vop3p : public Vop3p {
public:
  VPkAddF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMulF16Vop3p : public Vop3p {
public:
  VPkMulF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VDot2F32F16Vop3p : public Vop3p {
public:
  VDot2F32F16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot4I32Iu8Vop3p : public Vop3p {
public:
  VDot4I32Iu8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot4U32U8Vop3p : public Vop3p {
public:
  VDot4U32U8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot8I32Iu4Vop3p : public Vop3p {
public:
  VDot8I32Iu4Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot8U32U4Vop3p : public Vop3p {
public:
  VDot8U32U4Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot2F32Bf16Vop3p : public Vop3p {
public:
  VDot2F32Bf16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VPkMinNumF16Vop3p : public Vop3p {
public:
  VPkMinNumF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMaxNumF16Vop3p : public Vop3p {
public:
  VPkMaxNumF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMinimumF16Vop3p : public Vop3p {
public:
  VPkMinimumF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VPkMaximumF16Vop3p : public Vop3p {
public:
  VPkMaximumF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
};

class VFmaMixF32Vop3p : public Vop3p {
public:
  VFmaMixF32Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VFmaMixloF16Vop3p : public Vop3p {
public:
  VFmaMixloF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VFmaMixhiF16Vop3p : public Vop3p {
public:
  VFmaMixhiF16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot4F32Fp8Bf8Vop3p : public Vop3p {
public:
  VDot4F32Fp8Bf8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot4F32Bf8Fp8Vop3p : public Vop3p {
public:
  VDot4F32Bf8Fp8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot4F32Fp8Fp8Vop3p : public Vop3p {
public:
  VDot4F32Fp8Fp8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VDot4F32Bf8Bf8Vop3p : public Vop3p {
public:
  VDot4F32Bf8Bf8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF3216x16x16F16Vop3p : public Vop3p {
public:
  VWmmaF3216x16x16F16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF3216x16x16Bf16Vop3p : public Vop3p {
public:
  VWmmaF3216x16x16Bf16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF1616x16x16F16Vop3p : public Vop3p {
public:
  VWmmaF1616x16x16F16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaBf1616x16x16Bf16Vop3p : public Vop3p {
public:
  VWmmaBf1616x16x16Bf16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaI3216x16x16Iu8Vop3p : public Vop3p {
public:
  VWmmaI3216x16x16Iu8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaI3216x16x16Iu4Vop3p : public Vop3p {
public:
  VWmmaI3216x16x16Iu4Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF3216x16x16Fp8Fp8Vop3p : public Vop3p {
public:
  VWmmaF3216x16x16Fp8Fp8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF3216x16x16Fp8Bf8Vop3p : public Vop3p {
public:
  VWmmaF3216x16x16Fp8Bf8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF3216x16x16Bf8Fp8Vop3p : public Vop3p {
public:
  VWmmaF3216x16x16Bf8Fp8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaF3216x16x16Bf8Bf8Vop3p : public Vop3p {
public:
  VWmmaF3216x16x16Bf8Bf8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VWmmaI3216x16x32Iu4Vop3p : public Vop3p {
public:
  VWmmaI3216x16x32Iu4Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF3216x16x32F16Vop3p : public Vop3p {
public:
  VSwmmacF3216x16x32F16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF3216x16x32Bf16Vop3p : public Vop3p {
public:
  VSwmmacF3216x16x32Bf16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF1616x16x32F16Vop3p : public Vop3p {
public:
  VSwmmacF1616x16x32F16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacBf1616x16x32Bf16Vop3p : public Vop3p {
public:
  VSwmmacBf1616x16x32Bf16Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacI3216x16x32Iu8Vop3p : public Vop3p {
public:
  VSwmmacI3216x16x32Iu8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacI3216x16x32Iu4Vop3p : public Vop3p {
public:
  VSwmmacI3216x16x32Iu4Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacI3216x16x64Iu4Vop3p : public Vop3p {
public:
  VSwmmacI3216x16x64Iu4Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF3216x16x32Fp8Fp8Vop3p : public Vop3p {
public:
  VSwmmacF3216x16x32Fp8Fp8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF3216x16x32Fp8Bf8Vop3p : public Vop3p {
public:
  VSwmmacF3216x16x32Fp8Bf8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF3216x16x32Bf8Fp8Vop3p : public Vop3p {
public:
  VSwmmacF3216x16x32Bf8Fp8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

class VSwmmacF3216x16x32Bf8Bf8Vop3p : public Vop3p {
public:
  VSwmmacF3216x16x32Bf8Bf8Vop3p(const MachineInst *inst);
  void execute_impl(amdgpu::Wavefront &wf);
  Operand vdst;
  Operand src0;
  Operand src1;
  Operand src2;
};

} // namespace rdna4
} // namespace rocjitsu

#endif // ROCJITSU_ISA_ARCH_AMDGPU_RDNA4_VOP3P_H_
