name: hipfile-ci
run-name: Main hipFile CI workflow to coordinate jobs for a single platform

on:
  workflow_call:
    inputs:
      ci_image:
        description: "Full CI image name & tag"
        required: true
        type: string
      ci_image_nvidia:
        description: "Full CI image name & nvidia tag"
        required: true
        type: string
      platform:
        required: true
        type: string
      rocm_version:
        description: "Target ROCm MAJOR.MINOR.PATCH Version"
        required: true
        type: string

permissions:
  contents: read
  packages: read

jobs:
  build_and_test:
    uses: ./.github/workflows/hipfile-build.yml
    with:
      ci_image: ${{ inputs.ci_image }}
      cxx_compiler: amdclang++
      platform: ${{ inputs.platform }}
      rocm_version: ${{ inputs.rocm_version }}
      upload_artifacts: true

  build_and_test_cxx20:
    if: ${{ inputs.platform != 'rocky8' }}
    uses: ./.github/workflows/hipfile-build.yml
    with:
      ci_image: ${{ inputs.ci_image }}
      cxx_compiler: amdclang++
      cxx_standard: 20
      platform: ${{ inputs.platform }}
      rocm_version: ${{ inputs.rocm_version }}
      upload_artifacts: false
      generate_coverage: false

  # Try building on other compilers, but keep as separate job.
  # Removes issues regarding matrix job overwriting outputs and
  # does not propagate failures.
  build_and_test_other_compilers:
    strategy:
      fail-fast: false
      matrix:
        cxx_compiler:
          - clang++
          - g++
    uses: ./.github/workflows/hipfile-build.yml
    with:
      ci_image: ${{ inputs.ci_image }}
      cxx_compiler: ${{ matrix.cxx_compiler }}
      platform: ${{ inputs.platform }}
      rocm_version: ${{ inputs.rocm_version }}

  python_bindings:
    needs: [build_and_test]
    uses: ./.github/workflows/hipfile-python-bindings.yml
    with:
      ais_hipfile_pkg_dev_filename: ${{ needs.build_and_test.outputs.ais_hipfile_pkg_dev_filename }}
      ais_hipfile_pkg_filename: ${{ needs.build_and_test.outputs.ais_hipfile_pkg_filename }}
      ci_image: ${{ needs.build_and_test.outputs.ci_image }}
      platform: ${{ inputs.platform }}
      rocm_version: ${{ inputs.rocm_version }}

  AIS_system_tests:
    needs: [build_and_test]
    uses: ./.github/workflows/hipfile-ci-system.yml
    with:
      ais_hipfile_pkg_dev_filename: ${{ needs.build_and_test.outputs.ais_hipfile_pkg_dev_filename }}
      ais_hipfile_pkg_filename: ${{ needs.build_and_test.outputs.ais_hipfile_pkg_filename }}
      ci_image: ${{ needs.build_and_test.outputs.ci_image }}
      platform: ${{ inputs.platform }}
      rocm_version: ${{ inputs.rocm_version }}

  build_and_test_NVIDIA:
    if: ${{ !startsWith(inputs.rocm_version, '7.13.') }}
    uses: ./.github/workflows/hipfile-build-nvidia.yml
    with:
      ci_image: ${{ inputs.ci_image_nvidia }}
      platform: ${{ inputs.platform }}
      rocm_version: ${{ inputs.rocm_version }}
