# Run ShellCheck (https://www.shellcheck.net/) over shell scripts

name: "hipFile ShellCheck"

on:
  push:
    branches: [develop]
    paths:
      - 'projects/hipfile/**.sh'
      - '.github/workflows/hipfile-shellcheck.yml'
  pull_request:
    paths:
      - 'projects/hipfile/**.sh'
      - '.github/workflows/hipfile-shellcheck.yml'

permissions:
  contents: read

jobs:
  hipfile-shellcheck:
    name: "hipFile: Run ShellCheck over shell scripts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            projects/hipfile
            .github/workflows
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
