name: hipFile
run-name: Kicks off several hipFile CI workflows for various platforms

# In particular, this root workflow's only purpose is to allow
# us to put our entire CI in a matrix. It has the added benefit
# of not needing to specify our supported_platforms in multiple
# locations.
# We can consider moving the Pre-Checks here and passing them into
# the CI as an input.
on:
  pull_request:
    types: [opened, synchronize, reopened] # Defaults
    paths:
      - 'projects/hipfile/**'
      - '.github/workflows/hipfile-*.yml'
      - '!**/*.md'
      - '!**/*.rst'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  Linux:
    strategy:
      fail-fast: false
      matrix:
        supported_platforms:
          - rocky
          - suse
          - ubuntu
        rocm_versions:
          - 7.2.2
    uses: ./.github/workflows/hipfile-ci.yml
    with:
      platform: ${{ matrix.supported_platforms }}
      rocm_version: ${{ matrix.rocm_versions }}
