name: "hipFile clang-format"

on:
  push:
    branches: [develop]
    paths:
      - 'projects/hipfile/**/*.c'
      - 'projects/hipfile/**/*.cpp'
      - 'projects/hipfile/**/*.h'
      - 'projects/hipfile/.clang-format'
      - '.github/workflows/hipfile-clang-format.yml'
  pull_request:
    paths:
      - 'projects/hipfile/**/*.c'
      - 'projects/hipfile/**/*.cpp'
      - 'projects/hipfile/**/*.h'
      - 'projects/hipfile/.clang-format'
      - '.github/workflows/hipfile-clang-format.yml'

permissions:
  contents: read

jobs:
  hipfile-clang-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        sparse-checkout: |
          projects/hipfile
          .github/workflows

    - name: Install clang-format
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y clang-format-18

    - name: Run clang-format style check for C/C++ code
      uses: DoozyX/clang-format-lint-action@bcb4eb2cb0d707ee4f3e5cc3b456eb075f12cf73 # v0.20
      with:
        source: 'projects/hipfile'
        extensions: 'c,h,cpp'
        clangFormatVersion: 18
        style: file
