# Run pylint over the Python files

name: "hipFile pylint"

on:
  push:
    branches: [develop]
    paths:
      - 'projects/hipfile/**/*.py'
      - 'projects/hipfile/**/ais-check'
      - '.github/workflows/hipfile-pylint.yml'
  pull_request:
    paths:
      - 'projects/hipfile/**/*.py'
      - 'projects/hipfile/**/ais-check'
      - '.github/workflows/hipfile-pylint.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hipfile-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            projects/hipfile
            .github/workflows

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: 'pip'

      # requirements.in from the docs is needed to lint conf.py
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          python -m pip install black
          python -m pip install pytest
          pip install -r projects/hipfile/docs/sphinx/requirements.in

      - name: Lint all Python files
        run: |
          cd projects/hipfile
          FILES=$(find . -type f \( -name "*.py" -o -name "ais-check" \))
          if [ -z "$FILES" ]; then
            echo "No Python files found!"
            exit 1
          fi
          echo "Linting the following files:"
          echo "$FILES"
          python -m black --check --diff $FILES
          python -m pylint $FILES
