name: rocprofiler-compute Ubuntu 22.04

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/rocprofiler-compute-ubuntu-jammy.yml'
      - 'projects/rocprofiler-compute/**'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!projects/rocprofiler-compute/docs/**'
      - '!projects/rocprofiler-compute/docker/**'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-compute-ubuntu-jammy.yml'
      - 'projects/rocprofiler-compute/**'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!projects/rocprofiler-compute/docs/**'
      - '!projects/rocprofiler-compute/docker/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu-jammy:
    # The type of runner that the job will run on
    # https://hub.docker.com/r/rocm/dev-ubuntu-22.04/tags
    runs-on: ubuntu-latest
    container:
      image: rocm/dev-ubuntu-22.04:7.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install baseline OS dependencies
        run: |
          apt-get update
          apt-get install -y git
          apt-get install -y python3-pip
          apt-get install -y cmake

      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            projects/rocprofiler-compute
            shared/ctest
          set-safe-directory: true

      - name: Configure git safe directory
        run: git config --global --add safe.directory '*'

      - name: Install Python prereqs
        working-directory: projects/rocprofiler-compute
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-test.txt

      - name: Configure and install
        working-directory: projects/rocprofiler-compute
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/opt/rocprofiler-compute -DPYTEST_NUMPROCS=4 ..
          make install

      - name: CTest- Analyze Commands
        working-directory: projects/rocprofiler-compute
        run: |
          cd build
          ctest --verbose -R test_analyze_commands

      - name: CTest- Analyze Workloads
        working-directory: projects/rocprofiler-compute
        run: |
          cd build
          ctest --verbose -R test_analyze_workloads
