name: rocprofiler-compute GHCR Packages for CI Images

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/rocprofiler-compute-ghcr.yml'
      - 'projects/rocprofiler-compute/docker/**'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-compute-ghcr.yml'
      - 'projects/rocprofiler-compute/docker/**'

jobs:
  prepare_matrix_ci:
    if: github.repository == 'ROCm/rocm-systems'
    runs-on: ubuntu-latest
    outputs:
      containers_list: ${{ steps.generate_containers_list.outputs.containers_list }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-compute/docker

      - name: Generate containers list
        working-directory: projects/rocprofiler-compute/docker
        id: generate_containers_list
        run: |
          CONTAINERS_LIST=$(cat containers-ci.yml | yq '.matrix' -I=0 -o=json)
          echo "containers_list=$CONTAINERS_LIST" >> $GITHUB_OUTPUT

  rocprofiler-compute-ci-gfx:
    needs: prepare_matrix_ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.prepare_matrix_ci.outputs.containers_list) }}
        gpu: [ 'multiarch' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-compute
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker variables
        id: setup_vars_gfx
        run: |
          if [ ${{ matrix.system.distro }} = "opensuse" ]; then
            DISTRO_IMAGE="opensuse/leap"
          elif [ ${{ matrix.system.distro }} = "rhel" ]; then
            DISTRO_IMAGE="rockylinux/rockylinux"
          else
            DISTRO_IMAGE=${{ matrix.system.distro }}
          fi
          echo "distro_image=${DISTRO_IMAGE}" >> $GITHUB_OUTPUT

          if [ ${{ matrix.system.distro }} = "debian" ]; then
            DOCKER_FILE=Dockerfile.ubuntu.ci
          else
            DOCKER_FILE=Dockerfile.${{ matrix.system.distro }}.ci
          fi
          echo "docker_file=${DOCKER_FILE}" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/ROCm/rocprofiler-${{ matrix.system.distro }}

      - name: Build CI GFX Container (Does not Push on PR)
        id: docker_build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          file: projects/rocprofiler-compute/docker/${{ steps.setup_vars_gfx.outputs.docker_file }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            DISTRO=${{ steps.setup_vars_gfx.outputs.distro_image }}
            VERSION=${{ matrix.system.version }}
            GPU_TYPE=${{ matrix.gpu }}
          tags: |
            ghcr.io/rocm/rocprofiler-${{ matrix.system.distro }}:${{ matrix.system.version }}-compute-ci-${{ matrix.gpu }}
          labels: ${{ steps.meta.outputs.labels }}

      # Retry a copy of docker_build if Docker build failed due to intermittent failure
      - name: Build CI GFX Container Retry (Does not Push on PR)
        if: steps.docker_build.outcome != 'success'
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          file: projects/rocprofiler-compute/docker/${{ steps.setup_vars_gfx.outputs.docker_file }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            DISTRO=${{ steps.setup_vars_gfx.outputs.distro_image }}
            VERSION=${{ matrix.system.version }}
            GPU_TYPE=${{ matrix.gpu }}
          tags: |
            ghcr.io/rocm/rocprofiler-${{ matrix.system.distro }}:${{ matrix.system.version }}-compute-ci-${{ matrix.gpu }}
          labels: ${{ steps.meta.outputs.labels }}
