name: rocprofiler-systems Python Linting
run-name: Python

on:
  push:
    branches:
      - develop
    paths:
      - 'projects/rocprofiler-systems/**'
      - 'projects/rocprofiler-systems/source/python/gui/*.py'
      - 'projects/rocprofiler-systems/source/python/gui/**/*.py'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!docs/**'
      - '!projects/*/docs/**'
  pull_request:
    paths:
      - 'projects/rocprofiler-systems/**'
      - 'projects/rocprofiler-systems/source/python/gui/*.py'
      - 'projects/rocprofiler-systems/source/python/gui/**/*.py'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!docs/**'
      - '!projects/*/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v6
      with:
        sparse-checkout: projects/rocprofiler-systems
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: projects/rocprofiler-systems/source/python/gui
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: projects/rocprofiler-systems/source/python/gui
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # flake8 options are defined in setup.cfg
        flake8 . --count --statistics
