name: rocprofiler-systems Continuous Integration
run-name: rocprofiler-systems-ci

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Build mode'
        required: false
        default: 'continuous'
        type: choice
        options:
          - continuous
          - nightly
  push:
    branches: [ develop ]
    paths:
      - '.github/workflows/rocprofiler-systems-continuous-integration.yml'
      - 'projects/rocprofiler-systems/**'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!projects/rocprofiler-systems/docs/**'
      - '!projects/rocprofiler-systems/source/docs/**'
      - '!projects/rocprofiler-systems/source/python/gui/**'
      - '!projects/rocprofiler-systems/docker/**'
      - '!projects/rocprofiler-systems/CMakePresets.json'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-systems-continuous-integration.yml'
      - 'projects/rocprofiler-systems/**'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!projects/rocprofiler-systems/docs/**'
      - '!projects/rocprofiler-systems/source/docs/**'
      - '!projects/rocprofiler-systems/source/python/gui/**'
      - '!projects/rocprofiler-systems/docker/**'
      - '!projects/rocprofiler-systems/CMakePresets.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ROCPROFSYS_CI: ON
  ROCPROFSYS_TMPDIR: "%env{PWD}%/testing-tmp"
  ROCM_PATH: "/opt/rocm"

  EXCLUDED_TESTS: "fork.*|jacobi-usm-sys-run|jacobi-roctx.*|jpeg-decode-.*|matrix-exponential.*|selective-region-region-1-filter.*|selective-region-region-2-and-3.*|selective-region-no-marker-region-1-filter.*|kfd-.*|unified-memory-output-sys-run|rccl-alltoall-perf-sys-run"
  EXCLUDED_LABELS: "thread_limit"

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-systems/.github

      - name: Generate and output matrix
        id: generate_matrix
        working-directory: projects/rocprofiler-systems/.github
        run: |
          if [ '${{ github.event_name }}' = 'schedule' ] || [ '${{ inputs.mode }}' = 'nightly' ]; then
            MATRIX_CONTENT=$(cat ci-matrix.yml | yq '.matrix-nightly' -I=0 -o=json)
          else
            MATRIX_CONTENT=$(cat ci-matrix.yml | yq '.matrix-ci' -I=0 -o=json)
          fi
          echo "matrix=${MATRIX_CONTENT}" >> $GITHUB_OUTPUT

  ubuntu:
    name: Ubuntu ${{ matrix.system.os-release }} • ${{ matrix.system.arch }}
    needs: prepare_matrix
    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.prepare_matrix.outputs.matrix) }}
    runs-on: ${{ matrix.system.runner }}
    env:
      HIP_PLATFORM: "amd"
      ROCPROFSYS_CI: ON
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      ROCPROFSYS_KEEP_TEST_OUTPUT: '0'
    permissions:
      packages: read
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/rocm/rocprofiler-ubuntu:${{ matrix.system.os-release }}-systems-ci-multiarch
      # --env-file /etc/podinfo/gha-gpu-isolation-settings - Required for GPU isolation on OSSCI MIXXX runners
      options:
        --privileged
        --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --cap-add CAP_SYS_ADMIN
        --env-file /etc/podinfo/gha-gpu-isolation-settings

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            projects/rocprofiler-systems
            .gitmodules
          submodules: recursive

      - name: Setup Environment
        id: setup_env
        run: |
          if [ '${{ github.event_name }}' = 'schedule' ] || [ '${{ inputs.mode }}' = 'nightly' ]; then
            MODE=Nightly
            INCLUDED_LABELS="gpu"
            EXCLUDED_LABELS="${{ env.EXCLUDED_LABELS }}"
          else
            MODE=Continuous
            INCLUDED_LABELS="gpu"
            EXCLUDED_LABELS="${{ env.EXCLUDED_LABELS }}|slow"
          fi
          echo "mode=${MODE}" >> $GITHUB_OUTPUT
          echo "included_labels=${INCLUDED_LABELS}" >> $GITHUB_OUTPUT
          echo "excluded_labels=${EXCLUDED_LABELS}" >> $GITHUB_OUTPUT

      - name: Install MPI
        run: |
          apt install -y libopenmpi-dev
          echo "✅ MPI Installed!"

      - name: Install Latest Nightly ROCm
        run: |
          set -e
          mkdir ${{ env.ROCM_PATH }}
          TARBALL_ROCM_VERSION=$(ls /opt/*.tar.gz | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          tar -xf ${{ env.ROCM_PATH }}-${TARBALL_ROCM_VERSION}-multiarch.tar.gz -C ${{ env.ROCM_PATH }}
          echo "ROCm installed to: ${{ env.ROCM_PATH }}"
          echo "✅ ROCm Installation Complete!"

      - name: Output TheRock Manifest
        run: |
          cat ${{ env.ROCM_PATH }}/share/therock/therock_manifest.json

      - name: Install Python Test Dependencies
        timeout-minutes: 10
        shell: bash
        working-directory: projects/rocprofiler-systems
        run: |
          python3 -m pip install --break-system-packages -r requirements.txt

      - name: Configure, Build, and Test
        id: run_ci
        timeout-minutes: ${{ steps.setup_env.outputs.mode == 'Nightly' && 120 || 60 }}
        working-directory: projects/rocprofiler-systems
        run: |
          set -e
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config --global --add safe.directory ${PWD}
          INCLUDED_LABELS="${{ steps.setup_env.outputs.included_labels }}"
          LABEL_ARG=""
          if [ -n "${INCLUDED_LABELS}" ]; then
            LABEL_ARG="-L ${INCLUDED_LABELS}"
          fi
          PATH=${{ env.ROCM_PATH }}/bin:${{ env.ROCM_PATH }}/llvm/bin:$PATH \
          LD_LIBRARY_PATH=${{ env.ROCM_PATH }}/lib:${{ env.ROCM_PATH }}/llvm/lib:$LD_LIBRARY_PATH \
          python3 ./scripts/run-ci.py -B build \
            --name ${{ github.repository }}-${{ github.ref_name }}-ubuntu-${{ matrix.system.os-release }}-${{ matrix.system.gpu }} \
            --build-jobs 16 \
            --site ${{ matrix.system.runner }} \
            --mode ${{ steps.setup_env.outputs.mode }} \
            -- \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_PREFIX_PATH=${{ env.ROCM_PATH }} \
            -DCMAKE_INSTALL_PREFIX=/opt/rocprofiler-systems \
            -DROCPROFSYS_BUILD_DYNINST=ON \
            -DROCPROFSYS_BUILD_TBB=ON \
            -DROCPROFSYS_BUILD_ELFUTILS=ON \
            -DROCPROFSYS_BUILD_LIBIBERTY=ON \
            -DROCPROFSYS_BUILD_CI=ON \
            -DROCPROFSYS_BUILD_TESTING=ON \
            -DROCPROFSYS_USE_PYTHON=ON \
            -DROCPROFSYS_MAX_THREADS=64 \
            -- \
            -E "${{ env.EXCLUDED_TESTS }}" \
            -LE "${{ steps.setup_env.outputs.excluded_labels }}" \
            ${LABEL_ARG}

      - name: Check for Leftover Buffered Files
        timeout-minutes: 5
        working-directory: projects/rocprofiler-systems/
        run: |
          set -v
          if find /tmp -maxdepth 1 -name 'buffered*' -print -quit | grep -q .; then
            echo "Error: Found leftover buffered storage files in /tmp:"
            ls -lh /tmp/buffered*
            exit 1
          else
            echo "✓ No buffered storage files found in /tmp"
          fi

      - name: Output Logs
        if: failure() && steps.run_ci.outcome == 'failure'
        working-directory: projects/rocprofiler-systems
        run: |
          echo "❌ Run Failed: Now outputting LastTest.log files for detailed logs..."
          cat build/Testing/Temporary/LastTest*.log
