name: rocprofiler-systems Continuous Integration Containers
run-name: ci-containers

# nightly build
on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/rocprofiler-systems-containers.yml'
      - 'projects/rocprofiler-systems/docker/**'
      - 'projects/rocprofiler-systems/requirements.txt'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!docs/**'
      - '!projects/*/docs/**'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-systems-containers.yml'
      - 'projects/rocprofiler-systems/docker/**'
      - 'projects/rocprofiler-systems/requirements.txt'
      - '!**/*.md'
      - '!**/*.rtf'
      - '!**/*.rst'
      - '!**/.markdownlint-ci2.yaml'
      - '!**/.readthedocs.yaml'
      - '!**/.spellcheck.local.yaml'
      - '!**/.wordlist.txt'
      - '!docs/**'
      - '!projects/*/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  prepare_matrix_ci:
    if: github.repository == 'ROCm/rocm-systems'
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.generate_matrix_ci.outputs.distros }}
      rocm_versions: ${{ steps.generate_matrix_ci.outputs.rocm_versions }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-systems/docker

      - name: Output data for containers matrix
        working-directory: projects/rocprofiler-systems/docker
        id: generate_matrix_ci
        run: |
          DISTROS=$(cat containers-ci.yml | yq '.distros' -I=0 -o=json)
          echo "distros=$DISTROS" >> $GITHUB_OUTPUT
          ROCM_VERSIONS=$(cat containers-ci.yml | yq '.rocm-versions' -I=0 -o=json)
          echo "rocm_versions=$ROCM_VERSIONS" >> $GITHUB_OUTPUT

  rocprofiler-systems-ci:
    needs: prepare_matrix_ci
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.prepare_matrix_ci.outputs.distros) }}
        rocm-version: ${{ fromJSON(needs.prepare_matrix_ci.outputs.rocm_versions) }}
        exclude:
          - system: { distro: "debian", version: "12" }
            rocm-version: "6.3"
          - system: { distro: "rhel", version: "10" }
            rocm-version: "6.3"
          - system: { distro: "rhel", version: "10" }
            rocm-version: "6.4"
          - system: { distro: "rhel", version: "10" }
            rocm-version: "7.0"

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-systems/docker
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}
          password: ${{ secrets.ROCPROF_SYS_DOCKER_TOKEN }}

      - name: Build CI Container (PR - No Push)
        if: github.event_name == 'pull_request'
        timeout-minutes: 45
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 #v4.0.0
        with:
          retry_wait_seconds: 60
          timeout_minutes: 45
          max_attempts: 3
          command: |
            cd projects/rocprofiler-systems/docker
            ./build-docker-ci.sh \
              --distro ${{ matrix.system.distro }} \
              --versions ${{ matrix.system.version }} \
              --rocm-version ${{ matrix.rocm-version }} \
              --user ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }} \
              --jobs 2 \
              --elfutils-version 0.188 \
              --boost-version 1.79.0

      - name: Build CI Container (Push)
        if: github.event_name != 'pull_request'
        timeout-minutes: 45
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 #v4.0.0
        with:
          retry_wait_seconds: 60
          timeout_minutes: 45
          max_attempts: 3
          command: |
            cd projects/rocprofiler-systems/docker
            ./build-docker-ci.sh \
              --distro ${{ matrix.system.distro }} \
              --versions ${{ matrix.system.version }} \
              --rocm-version ${{ matrix.rocm-version }} \
              --user ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }} \
              --jobs 2 \
              --elfutils-version 0.188 \
              --boost-version 1.79.0 \
              --push

  prepare_matrix_release:
    if: github.repository == 'ROCm/rocm-systems'
    runs-on: ubuntu-latest
    outputs:
      matrix_data: ${{ steps.generate_matrix_release.outputs.matrix_data }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-systems

      - name: Output data for containers matrix
        working-directory: projects/rocprofiler-systems/docker
        id: generate_matrix_release
        run: |
          MATRIX_CONTENT=$(cat containers.yml | yq '.matrix' -I=0 -o=json)
          echo "matrix_data=$MATRIX_CONTENT" >> $GITHUB_OUTPUT

  rocprofiler-systems-release:
    needs: prepare_matrix_release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare_matrix_release.outputs.matrix_data) }}

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: projects/rocprofiler-systems

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}
          password: ${{ secrets.ROCPROF_SYS_DOCKER_TOKEN }}

      - name: Build Base Container (PR - No Push)
        if: github.event_name == 'pull_request'
        timeout-minutes: 45
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 #v4.0.0
        with:
          retry_wait_seconds: 60
          timeout_minutes: 45
          max_attempts: 3
          command: |
            cd projects/rocprofiler-systems/docker
            ./build-docker.sh \
              --distro ${{ matrix.os-distro }} \
              --versions ${{ matrix.os-version }} \
              --rocm-versions ${{ matrix.rocm-version }} \
              --user ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}

      - name: Build Base Container (Push)
        if: github.event_name != 'pull_request'
        timeout-minutes: 45
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 #v4.0.0
        with:
          retry_wait_seconds: 60
          timeout_minutes: 45
          max_attempts: 3
          command: |
            cd projects/rocprofiler-systems/docker
            ./build-docker.sh \
              --distro ${{ matrix.os-distro }} \
              --versions ${{ matrix.os-version }} \
              --rocm-versions ${{ matrix.rocm-version }} \
              --user ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }} \
              --push
