name: TheRock CI Nightly

on:
  schedule:
    - cron: "0 7 * * *" # Runs nightly at 7 AM UTC
  workflow_dispatch:
    inputs:
      projects:
        type: string
        description: "Insert space-separated list of projects to test or 'all' to test all projects. ex: 'projects/clr projects/rocminfo'"
      linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to build and test. ex: gfx94X, gfx950"
        default: ""
      windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to build and test. ex: gfx1151"
        default: ""

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-24.04
    env:
      # The commit being checked out is the merge commit for a PR. Its first
      # parent will be the tip of the base branch.
      BASE_REF: HEAD^
    outputs:
      linux_projects: ${{ steps.linux_projects.outputs.projects }}
      windows_projects: ${{ steps.windows_projects.outputs.projects }}
      run_linux_rccl_ci: ${{ steps.linux_projects.outputs.run_linux_rccl_ci }}
      package_version: ${{ steps.rocm_package_version.outputs.rocm_package_version }}
      linux_package_targets: ${{ steps.configure_linux.outputs.package_targets }}
      windows_package_targets: ${{ steps.configure_windows.outputs.package_targets }}
      linux_build_runs_on: ${{ steps.linux_projects.outputs.build_runs_on }}
      windows_build_runs_on: ${{ steps.windows_projects.outputs.build_runs_on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github
          sparse-checkout-cone-mode: true
          fetch-depth: 2

      - name: Checkout TheRock repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "ROCm/TheRock"
          path: TheRock
          ref: f1e3fc2311fde45bf3e17b0e3349200be9caa4b4 # 2026-06-23

      - name: Checkout CI config
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ROCm/therock-ci-config
          ref: main
          path: ci-config
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic requests

      - name: Determine Linux projects to run
        id: linux_projects
        env:
          PROJECTS: ${{ inputs.projects }}
          PLATFORM: "linux"
        run: |
          python .github/scripts/therock_configure_ci.py

      - name: Determine Windows projects to run
        id: windows_projects
        env:
          PROJECTS: ${{ inputs.projects }}
          PLATFORM: "windows"
        run: |
          python .github/scripts/therock_configure_ci.py

      - name: Compute package version
        id: rocm_package_version
        run: |
          python TheRock/build_tools/compute_rocm_package_version.py --release-type=dev

      - name: Fetch Linux targets for build and test
        env:
          THEROCK_PACKAGE_PLATFORM: "linux"
          AMDGPU_FAMILIES: ${{ inputs.linux_amdgpu_families || 'gfx94X, gfx950' }}
          CI_CONFIG_PATH: ci-config
        id: configure_linux
        run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py

      - name: Fetch Windows targets for build and test
        env:
          THEROCK_PACKAGE_PLATFORM: "windows"
          AMDGPU_FAMILIES: ${{ inputs.windows_amdgpu_families || 'gfx1151' }}
          CI_CONFIG_PATH: ci-config
        id: configure_windows
        run: python ./TheRock/build_tools/github_actions/fetch_package_targets.py

  therock-ci-linux:
    name: Linux (${{ matrix.projects.projects_to_test }} | ${{ matrix.target_bundle.amdgpu_family }})
    permissions:
      contents: read
      id-token: write
    needs: setup
    if: ${{ needs.setup.outputs.linux_projects != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.setup.outputs.linux_projects) }}
        target_bundle: ${{ fromJSON(needs.setup.outputs.linux_package_targets) }}
    uses: ./.github/workflows/therock-ci-linux.yml
    secrets: inherit
    with:
      cmake_options: ${{ matrix.projects.cmake_options }}
      projects_to_test: ${{ matrix.projects.projects_to_test }}
      package_version: ${{ needs.setup.outputs.package_version }}
      amdgpu_families: ${{ matrix.target_bundle.amdgpu_family }}
      test_runs_on: ${{ matrix.target_bundle.test_machine }}
      build_runs_on: ${{ needs.setup.outputs.linux_build_runs_on }}

  therock-rccl-ci-linux:
    name: TheRock RCCL CI Linux
    needs: setup
    if: ${{ needs.setup.outputs.run_linux_rccl_ci == 'true' }}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        amdgpu_family: [gfx94X-dcgpu, gfx950-dcgpu]
    uses: ./.github/workflows/therock-rccl-ci-linux.yml
    secrets: inherit
    with:
      amdgpu_families: ${{ matrix.amdgpu_family }}
      artifact_group: ${{ matrix.amdgpu_family }}
      package_version: ${{ needs.setup.outputs.package_version }}
      cmake_options: >
        -DTHEROCK_ENABLE_ALL=OFF
        -DTHEROCK_BUILD_TESTING=ON
        -DTHEROCK_BUNDLE_SYSDEPS=ON
        -DTHEROCK_ENABLE_COMM_LIBS=ON
        -DTHEROCK_ENABLE_ROCPROFV3=ON
        -DTHEROCK_ENABLE_MPI=ON

  therock-ci-windows:
    name: Windows (${{ matrix.projects.projects_to_test }} | ${{ matrix.target_bundle.amdgpu_family }})
    permissions:
      contents: read
      id-token: write
    needs: setup
    if: ${{ needs.setup.outputs.windows_projects != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.setup.outputs.windows_projects) }}
        target_bundle: ${{ fromJSON(needs.setup.outputs.windows_package_targets) }}
    uses: ./.github/workflows/therock-ci-windows.yml
    secrets: inherit
    with:
      cmake_options: ${{ matrix.projects.cmake_options }}
      projects_to_test: ${{ matrix.projects.projects_to_test }}
      package_version: ${{ needs.setup.outputs.package_version }}
      amdgpu_families: ${{ matrix.target_bundle.amdgpu_family }}
      test_runs_on: ${{ matrix.target_bundle.test_machine }}
      build_runs_on: ${{ needs.setup.outputs.windows_build_runs_on }}
